#!/usr/bin/env python3
"""Generate a BearSSL single-RSA trust-anchor C table from a PEM certificate.

This intentionally implements only the small DER subset needed by the local
HTTPS CI certificate generated by the TLS harness: an X.509 certificate with an
RSA SubjectPublicKeyInfo.  It avoids requiring the hosted `brssl` tool in CI.
"""

from __future__ import annotations

import ssl
import sys
from pathlib import Path


def die(message: str) -> None:
    print(f"local-ta-from-cert: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_tlv(data: bytes, offset: int) -> tuple[int, int, int, int, int]:
    if offset >= len(data):
        die("truncated DER")
    tag = data[offset]
    pos = offset + 1
    if pos >= len(data):
        die("missing DER length")
    first = data[pos]
    pos += 1
    if first & 0x80:
        count = first & 0x7F
        if count == 0 or count > 4 or pos + count > len(data):
            die("unsupported DER length")
        length = int.from_bytes(data[pos : pos + count], "big")
        pos += count
    else:
        length = first
    end = pos + length
    if end > len(data):
        die("DER value exceeds input")
    return tag, offset, pos, end, end


def children(data: bytes, start: int, end: int) -> list[tuple[int, int, int, int]]:
    out: list[tuple[int, int, int, int]] = []
    pos = start
    while pos < end:
        tag, item_start, content_start, item_end, pos = read_tlv(data, pos)
        out.append((tag, item_start, content_start, item_end))
    if pos != end:
        die("DER child parse ended out of bounds")
    return out


def expect_sequence(data: bytes, offset: int = 0) -> tuple[int, int]:
    tag, _start, content_start, end, next_offset = read_tlv(data, offset)
    if tag != 0x30:
        die(f"expected DER SEQUENCE, got tag 0x{tag:02x}")
    if offset == 0 and next_offset != len(data):
        die("trailing data after top-level DER SEQUENCE")
    return content_start, end


def integer_bytes(data: bytes, item: tuple[int, int, int, int]) -> bytes:
    tag, _start, content_start, end = item
    if tag != 0x02:
        die(f"expected INTEGER, got tag 0x{tag:02x}")
    value = data[content_start:end]
    while len(value) > 1 and value[0] == 0:
        value = value[1:]
    return value


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("\t" + ", ".join(f"0x{byte:02X}" for byte in chunk) + ("," if offset + 12 < len(data) else ""))
    lines.append("};")
    return "\n".join(lines)


def generate(cert_pem: Path) -> str:
    der = ssl.PEM_cert_to_DER_cert(cert_pem.read_text())
    cert_start, cert_end = expect_sequence(der)
    cert_items = children(der, cert_start, cert_end)
    if len(cert_items) < 1 or cert_items[0][0] != 0x30:
        die("certificate missing tbsCertificate")
    _tbs_tag, _tbs_start, tbs_content, tbs_end = cert_items[0]
    tbs_items = children(der, tbs_content, tbs_end)
    index = 1 if tbs_items and tbs_items[0][0] == 0xA0 else 0
    # serialNumber, signature, issuer, validity, subject, subjectPublicKeyInfo
    if len(tbs_items) < index + 6:
        die("tbsCertificate missing subject or public key")
    subject = tbs_items[index + 4]
    spki = tbs_items[index + 5]
    subject_der = der[subject[1] : subject[3]]

    if spki[0] != 0x30:
        die("subjectPublicKeyInfo is not a SEQUENCE")
    spki_items = children(der, spki[2], spki[3])
    if len(spki_items) != 2 or spki_items[1][0] != 0x03:
        die("subjectPublicKeyInfo does not contain a BIT STRING public key")
    bit_string = der[spki_items[1][2] : spki_items[1][3]]
    if not bit_string or bit_string[0] != 0:
        die("unsupported non-zero-unused-bits public key")
    rsa_der = bit_string[1:]
    rsa_start, rsa_end = expect_sequence(rsa_der)
    rsa_items = children(rsa_der, rsa_start, rsa_end)
    if len(rsa_items) < 2:
        die("RSA public key missing modulus or exponent")
    modulus = integer_bytes(rsa_der, rsa_items[0])
    exponent = integer_bytes(rsa_der, rsa_items[1])

    return "\n\n".join(
        [
            c_array("TA0_DN", subject_der),
            c_array("TA0_RSA_N", modulus),
            c_array("TA0_RSA_E", exponent),
            """static const br_x509_trust_anchor TAs[1] = {
\t{
\t\t{ (unsigned char *)TA0_DN, sizeof TA0_DN },
\t\tBR_X509_TA_CA,
\t\t{
\t\t\tBR_KEYTYPE_RSA,
\t\t\t{ .rsa = {
\t\t\t\t(unsigned char *)TA0_RSA_N, sizeof TA0_RSA_N,
\t\t\t\t(unsigned char *)TA0_RSA_E, sizeof TA0_RSA_E,
\t\t\t} }
\t\t}
\t}
};

#define TAs_NUM   1
""",
        ]
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        die("usage: local-ta-from-cert.py <cert.pem> <out.c>")
    out = generate(Path(argv[1]))
    Path(argv[2]).write_text(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
