// Bare-metal riscv64 M-mode (`-bios none`) DNS->HTTP runtime — in PURE MC.
// The all-MC replacement for kernel/drivers/virtio/dns_runtime.c. Resolves a hostname
// via a real DNS A-query over UDP, then TCP-GETs the resolved IP — driving the EXISTING
// MC path in tests/qemu/net/dns_http_demo.mc. Serves BOTH the dns-test and
// google-http-test gates.
//
// Same boot-seam shape as net/http_get; the per-invocation config the C runtime took via
// -D (DNS server IP, HTTP port, hostname, optional HTTP request override) is threaded in
// as a generated MC unit (mc_dns_server_ip/mc_http_port/mc_dns_hostname/mc_http_request),
// the same way the BearSSL epoch is — MC has no -D. Platform = the shared mmode_dma_time.mc.

import "kernel/arch/riscv64/sbi_virtio_probe.mc";
import "tests/qemu/net/dns_http_demo.mc"; // dns_http_drive / dns_resolved_ip / http_resp_* / dns_host_* / dns_req_*

// Per-invocation config, generated by the harness (replaces -DDNS_SERVER_IP / -DHTTP_PORT
// / -DDNS_HOSTNAME / -DHTTP_REQUEST). mc_http_request returns "" when no override is set.
extern fn mc_dns_server_ip() -> u32;
extern fn mc_http_port() -> u16;
extern fn mc_dns_hostname() -> *const u8;
extern fn mc_http_request() -> *const u8;

const VIRTIO_ID_NET: u32 = 1;
const UART_THR: usize = 0x1000_0000;
const FINISHER: usize = 0x0010_0000;
const FINISHER_HALT: u32 = 0x5555;

global g_rx_desc: DescTable;
global g_rx_avail: VringAvail;
global g_rx_used: VringUsed;
global g_tx_desc: DescTable;
global g_tx_avail: VringAvail;
global g_tx_used: VringUsed;
global g_rxq: Virtq;
global g_txq: Virtq;
global g_framebuf: [2048]u8;

fn uputc(c: u8) -> void {
    unsafe { raw.store<u8>(phys(UART_THR), c); }
}
fn uputs(s: *const u8) -> void {
    let base: usize = s as usize;
    var i: usize = 0;
    while true {
        var b: u8 = 0;
        unsafe { b = raw.load<u8>(phys(base + i)); }
        if b == 0 { break; }
        uputc(b);
        i = i + 1;
    }
}
fn uputhex(v: u64) -> void {
    uputc(48); uputc(120); // "0x"
    var s: i32 = 60;
    while s >= 0 {
        let nib: u64 = (v >> (s as u64)) & 0xF;
        if nib < 10 { uputc((48 + nib) as u8); } else { uputc((87 + nib) as u8); }
        s = s - 4;
    }
}
// Print one decimal octet (0..255), no leading zeros.
fn put_octet(o: u32) -> void {
    if o == 0 { uputc(48); return; }
    var tmp: [3]u8 = uninit;
    var n: i32 = 0;
    var v: u32 = o;
    while v != 0 {
        tmp[n as usize] = (48 + (v % 10)) as u8;
        v = v / 10;
        n = n + 1;
    }
    while n > 0 {
        n = n - 1;
        uputc(tmp[n as usize]);
    }
}
// Print a host-order IPv4 u32 as dotted-quad.
fn put_ip(ip: u32) -> void {
    var s: i32 = 24;
    while s >= 0 {
        put_octet((ip >> (s as u32)) & 0xFF);
        if s != 0 { uputc(46); } // '.'
        s = s - 8;
    }
}
fn halt() -> void {
    unsafe { raw.store<u32>(phys(FINISHER), FINISHER_HALT); }
    while true {}
}

fn dump_response() -> void {
    let n: usize = http_resp_len();
    uputs("RESP-LEN=");
    uputhex(n as u64);
    uputc(10);
    uputs("RESP-BEGIN\n");
    var i: usize = 0;
    while i < n {
        uputc(http_resp_byte(i));
        i = i + 1;
    }
    uputs("\nRESP-END\n");
}

export fn test_main() -> void {
    let regs: MmioPtr<VirtioMmio> = find_virtio_device(VIRTIO_ID_NET);
    if !virtio_device_present(regs) {
        uputs("NODEV\n");
        halt();
    }

    g_rxq.desc = &g_rx_desc;
    g_rxq.avail = &g_rx_avail;
    g_rxq.used = &g_rx_used;
    g_txq.desc = &g_tx_desc;
    g_txq.avail = &g_tx_avail;
    g_txq.used = &g_tx_used;

    let dns_ip: u32 = mc_dns_server_ip();
    let http_port: u16 = mc_http_port();

    // Push the hostname to resolve into the kernel.
    let host: usize = mc_dns_hostname() as usize;
    dns_host_reset();
    uputs("dns-http booting; resolving ");
    var hi: usize = 0;
    while true {
        var b: u8 = 0;
        unsafe { b = raw.load<u8>(phys(host + hi)); }
        if b == 0 { break; }
        uputc(b);
        dns_host_push(b);
        hi = hi + 1;
    }
    uputs(" via DNS server ");
    put_ip(dns_ip);
    uputs(" port ");
    uputhex(http_port as u64);
    uputc(10);

    // Optional HTTP request override (empty string -> use the kernel's built-in default).
    let req: usize = mc_http_request() as usize;
    var first: u8 = 0;
    unsafe { first = raw.load<u8>(phys(req)); }
    if first != 0 {
        dns_req_reset();
        var ri: usize = 0;
        while true {
            var rb: u8 = 0;
            unsafe { rb = raw.load<u8>(phys(req + ri)); }
            if rb == 0 { break; }
            dns_req_push(rb);
            ri = ri + 1;
        }
    }

    let rxbuf: usize = (&g_framebuf[0]) as usize;
    let st: u32 = dns_http_drive(regs, &g_rxq, &g_txq, dns_ip, http_port, rxbuf, 2048);
    uputs("DRIVE-STATUS=");
    uputhex(st as u64);
    uputc(10);

    let ip: u32 = dns_resolved_ip();
    if ip != 0 {
        uputs("RESOLVED-IP=");
        uputhex(ip as u64);
        uputs(" (");
        put_ip(ip);
        uputs(")\n");
    }

    if st == 0 { uputs("NIC-OR-ARP-FAILED\n"); }
    else { if st == 5 { uputs("DNS-QUERY-TX-FAILED\n"); }
    else { if st == 6 { uputs("DNS-NO-RESPONSE\n"); }
    else { if st == 1 { uputs("NO-SYN-ACK\n"); }
    else { if st == 2 { uputs("HANDSHAKE-OK-GET-TX-FAILED\n"); }
    else { if st == 3 { uputs("HANDSHAKE+GET-OK-NO-RESPONSE\n"); }
    else { if st == 4 { uputs("HANDSHAKE+GET+RESPONSE-OK\n"); }
    else { uputs("UNKNOWN\n"); } } } } } } }

    if st == 4 {
        dump_response();
        uputs("DNS-HTTP-OK\n");
    }
    halt();
}

#[naked]
#[section(".text.start")]
export fn _start() -> void {
    asm opaque volatile {
        "la sp, _stack_top\n call test_main\n 1: j 1b"
    }
}
