// examples/apps/wasm_host — the FIXED, generic WASM host (the WASM analogue of qjs_host.c, and the
// replacement the migration is built toward). It never changes per agent: it instantiates the
// vendored wasm3 interpreter, links the reusable WASI Preview 1 shim (examples/apps/wasm/wasi_shim),
// loads a guest .wasm module, and runs its `_start`. Shipping a different agent changes only the
// .wasm — exactly the "standard, reusable boundary" the plan replaces the bespoke JS glue with
// (docs/wasm-migration-plan.md §1).
//
// Phase 1 confined bring-up (gate wasm-wasi-hello-test, mirrors qjs-confined-test): the guest is a
// stock wasm32-wasi binary embedded at build time; the host runs CONFINED in an isolated Sv39
// U-mode space and reaches the kernel ONLY through the syscall ABI (here: SYS_WRITE via the shim's
// fd_write, and SYS_EXIT when main returns). A later phase swaps the embedded blob for the §0
// capability ingress (SYS_READ), keeping everything below this U-mode payload unchanged.

#include "wasm3.h"
#include "wasi_shim.h"

#include <stdint.h>
#include <stddef.h>

#include "wasm_blob.h"  // generated by the harness: const unsigned char wasm_blob[]; unsigned int wasm_blob_len;

extern long sys_write(unsigned long fd, const void *buf, unsigned long len);

static unsigned long cstrlen(const char *s) { unsigned long n = 0; while (s[n]) n++; return n; }
static void emit(const char *s) { sys_write(1, s, cstrlen(s)); }

static int fail(const char *stage, M3Result res) {
    emit("wasm3: "); emit(stage); emit(": "); emit(res ? res : "(null)"); emit("\n");
    return 1;
}

int main(void) {
    IM3Environment env = m3_NewEnvironment();
    if (!env) { emit("wasm3: no environment\n"); return 1; }

    // 256 KiB wasm operand stack (lives in the libc malloc arena, not the native C stack).
    IM3Runtime runtime = m3_NewRuntime(env, 256 * 1024, NULL);
    if (!runtime) { emit("wasm3: no runtime\n"); m3_FreeEnvironment(env); return 1; }

    IM3Module module;
    M3Result res = m3_ParseModule(env, &module, wasm_blob, wasm_blob_len);
    if (res) return fail("parse", res);

    res = m3_LoadModule(runtime, module);  // runtime owns the module after a successful load
    if (res) return fail("load", res);

    res = wasm_wasi_link(module);
    if (res) return fail("link wasi", res);

    IM3Function start;
    res = m3_FindFunction(&start, runtime, "_start");
    if (res) return fail("find _start", res);

    res = m3_CallV(start);
    if (res && res != wasm_wasi_proc_exit_result) return fail("run", res);

    m3_FreeRuntime(runtime);
    m3_FreeEnvironment(env);
    return wasm_wasi_exit_code;
}
