// examples/apps/wasm_agent — the confined wasm3 agent front-end (Phase-0 bring-up), the WASM
// analogue of examples/apps/qjs_agent.c. NOT a general engine yet: it instantiates the vendored
// wasm3 interpreter (third_party/wasm3), links a minimal WASI-shaped import set
// (fd_write -> SYS_WRITE, proc_exit -> exit), loads a fixed embedded .wasm module, and runs its
// exported `_start`. The module prints a marker via fd_write and exits.
//
// Phase 1 replaces the embedded blob with the capability ingress (SYS_READ) and a real WASI P1
// shim; the kernel, syscall ABI, and brokers below this U-mode payload are unchanged
// (docs/wasm-migration-plan.md §1, §7).
//
// The engine builds freestanding against the all-MC libc + openlibm exactly like the QuickJS
// payload; see third_party/wasm3/VENDOR.md for the (printf-free) compile set.

#include "wasm3.h"

#include <stdint.h>
#include <stddef.h>

#include "wasm_blob.h"  // generated by the harness: const unsigned char wasm_blob[]; unsigned int wasm_blob_len;

// The platform runtime (tests/qemu/lang/wasm_runtime.mc) provides the console syscall.
extern long sys_write(unsigned long fd, const void *buf, unsigned long len);

static unsigned long cstrlen(const char *s) { unsigned long n = 0; while (s[n]) n++; return n; }
static void emit(const char *s) { sys_write(1, s, cstrlen(s)); }

// m3_info.c (the printf disassembler) is excluded from the freestanding build; provide the one
// symbol m3_FreeRuntime references unconditionally. See third_party/wasm3/VENDOR.md.
void m3_PrintProfilerInfo(void) {}

// proc_exit unwinds the interpreter by returning a sentinel M3Result that main() recognizes as a
// clean exit rather than a trap. (M3Result is `const char *`; the sentinel's identity is its
// address.)
static const char *const c_proc_exit = "wasm3-host: guest called proc_exit";
static int g_exit_code = 0;

// WASI fd_write(fd, *iovs, iovs_len, *nwritten) -> errno. iovs is an array of (buf, len) pairs
// whose buf is an offset into the guest's linear memory; we resolve each to a host pointer,
// bounds-check it against the instance memory, and route the bytes to the console syscall.
m3ApiRawFunction(host_fd_write) {
    m3ApiReturnType(uint32_t)
    m3ApiGetArg    (uint32_t, fd)
    m3ApiGetArgMem (const uint32_t *, iovs)
    m3ApiGetArg    (uint32_t, iovs_len)
    m3ApiGetArgMem (uint32_t *, nwritten)

    m3ApiCheckMem(iovs, (uint64_t)iovs_len * 8);

    uint32_t total = 0;
    for (uint32_t i = 0; i < iovs_len; i++) {
        uint32_t off = iovs[i * 2 + 0];
        uint32_t len = iovs[i * 2 + 1];
        void *p = m3ApiOffsetToPtr(off);
        m3ApiCheckMem(p, len);
        sys_write(fd, p, len);
        total += len;
    }
    if (nwritten) {
        m3ApiCheckMem(nwritten, 4);
        *nwritten = total;
    }
    m3ApiReturn(0);  // __WASI_ERRNO_SUCCESS
}

// WASI proc_exit(code) -> noreturn.
m3ApiRawFunction(host_proc_exit) {
    m3ApiGetArg(uint32_t, code)
    g_exit_code = (int)code;
    m3ApiTrap(c_proc_exit);
}

static int fail(const char *stage, M3Result res) {
    emit("wasm3: ");
    emit(stage);
    emit(": ");
    emit(res ? res : "(null)");
    emit("\n");
    return 1;
}

int main(void) {
    IM3Environment env = m3_NewEnvironment();
    if (!env) { emit("wasm3: no environment\n"); return 1; }

    // 8192 operand-stack slots (64 KiB). The interpreter chains op functions via tail calls, so
    // the *native* C stack stays shallow; this is the WASM operand stack.
    IM3Runtime runtime = m3_NewRuntime(env, 8192, NULL);
    if (!runtime) { emit("wasm3: no runtime\n"); m3_FreeEnvironment(env); return 1; }

    IM3Module module;
    M3Result res = m3_ParseModule(env, &module, wasm_blob, wasm_blob_len);
    if (res) return fail("parse", res);

    res = m3_LoadModule(runtime, module);
    if (res) return fail("load", res);  // module is owned by the runtime after a successful load

    res = m3_LinkRawFunction(module, "wasi_snapshot_preview1", "fd_write", "i(iiii)", &host_fd_write);
    if (res && res != m3Err_functionLookupFailed) return fail("link fd_write", res);
    res = m3_LinkRawFunction(module, "wasi_snapshot_preview1", "proc_exit", "v(i)", &host_proc_exit);
    if (res && res != m3Err_functionLookupFailed) return fail("link proc_exit", res);

    IM3Function start;
    res = m3_FindFunction(&start, runtime, "_start");
    if (res) return fail("find _start", res);

    res = m3_CallV(start);
    if (res && res != c_proc_exit) return fail("call", res);

    m3_FreeRuntime(runtime);
    m3_FreeEnvironment(env);
    return g_exit_code;
}
