// HTTPS-GET runtime: the REAL TLS bridge. Platform glue (virtio-mmio discovery, a
// bump DMA allocator, the vring memory, a virtio-rng entropy source, the clock seam)
// that drives a REAL BearSSL TLS 1.2 client over the MC kernel's hand-rolled TCP
// (tests/qemu/tls/tls_demo.mc) under QEMU user networking, fetching real HTTPS
// content and verifying the decrypted response.
//
// The crux is THE BRIDGE: BearSSL's record layer is wired to our TCP via two
// callbacks -- low_write -> tls_send (one PSH|ACK segment) and low_read -> tls_recv
// (the next inbound data segment, ACKed). The TLS engine, the X.509 minimal
// validator, the trust anchor(s), the injected entropy and the validation time are
// all set up here; then br_sslio_* runs a genuine handshake + an HTTPS GET and we
// check the decrypted body for the expected token.
//
// Compile-time parameters (the test scripts override via -D):
//   MC_BUILD_EPOCH : unix seconds, threaded in for X.509 validity (the clock seam).
//   HTTPS_PORT     : the TCP port to connect to (local test). Ignored when TLS_GOOGLE.
//   TLS_SERVERNAME : SNI / cert-name to validate against ("host.test" or "google.com").
//   TLS_HOSTHDR    : the HTTP Host: header value.
//   TLS_GOOGLE     : if defined, resolve TLS_DNSHOST via DNS (DNS_SERVER_IP) and
//                    connect to the resolved IP on :443 (the real-google path).
//   TLS_DNSHOST    : the name to resolve when TLS_GOOGLE (e.g. "google.com").
//   DNS_SERVER_IP  : the DNS server, host-order u32 (TLS_GOOGLE only).
// The trust anchor C is included (google_ta.c when TLS_GOOGLE, else local_ta.c); both
// define `TAs[]` + `TAs_NUM`.
#include <stdint.h>
#include <stddef.h>

#include "bearssl.h"

#ifndef MC_BUILD_EPOCH
#define MC_BUILD_EPOCH 0
#endif
#ifndef HTTPS_PORT
#define HTTPS_PORT 8443
#endif
#ifndef TLS_SERVERNAME
#define TLS_SERVERNAME "host.test"
#endif
#ifndef TLS_HOSTHDR
#define TLS_HOSTHDR "host.test"
#endif
#ifndef DNS_SERVER_IP
#define DNS_SERVER_IP 0x0A000203u /* 10.0.2.3 slirp DNS forwarder */
#endif
#ifndef TLS_DNSHOST
#define TLS_DNSHOST "google.com"
#endif

#define LOCAL_IP 0x0A000202u /* 10.0.2.2 slirp gateway -> host loopback */

// Embed the trust anchor set generated by `brssl ta`. Both files define TAs/TAs_NUM.
#ifdef TLS_GOOGLE
#include "google_ta.c"
#else
#include "local_ta.c"
#endif

// ------------------------------------------------------------------- clock seam
// PRIMARY wall-clock: the real goldfish-RTC, read via the kernel/core/time.mc seam
// (linked in as time.o). mc_build_epoch is now only a documented FALLBACK for when
// the RTC is absent/unpopulated (reads back an implausible epoch).
const uint64_t mc_build_epoch = (uint64_t)MC_BUILD_EPOCH;
uint64_t time_now_epoch(void); // kernel/core/time.mc — real wall-clock, seconds

#define CLINT_MTIME 0x0200BFF8UL
uint64_t mc_read_ticks(void) { return *(volatile uint64_t *)CLINT_MTIME; }
void mc_udelay(uint32_t us) {
    uint64_t target = *(volatile uint64_t *)CLINT_MTIME + (uint64_t)us * 10u;
    while (*(volatile uint64_t *)CLINT_MTIME < target) { }
}

// ----- virtqueue structs matching the MC layout (std/virtqueue.mc) -----
typedef struct VringDesc { uint64_t addr; uint32_t len; uint16_t flags; uint16_t next; } VringDesc;
typedef struct DescTable { VringDesc d[8]; } DescTable;
typedef struct VringAvail { uint16_t flags; uint16_t idx; uint16_t ring[8]; uint16_t used_event; } VringAvail;
typedef struct UsedElem { uint32_t id; uint32_t len; } UsedElem;
typedef struct VringUsed { uint16_t flags; uint16_t idx; UsedElem ring[8]; uint16_t avail_event; } VringUsed;
typedef struct mc_array_u64_8 { uint64_t elems[8]; } mc_array_u64_8;
typedef struct mc_array_u32_8 { uint32_t elems[8]; } mc_array_u32_8;
typedef struct mc_array_bool_8 { uint8_t elems[8]; } mc_array_bool_8;
typedef struct Virtq {
    DescTable *desc; VringAvail *avail; VringUsed *used;
    uint16_t size; uint16_t free_head; uint16_t num_free; uint16_t last_used;
    mc_array_u64_8 inflight_addr;
    mc_array_u32_8 inflight_len;
    mc_array_bool_8 inflight_present;
} Virtq;
typedef struct CpuBuffer { uintptr_t dev_addr; uintptr_t cpu_addr; uintptr_t len; } CpuBuffer;
typedef struct DeviceBuffer { uintptr_t dev_addr; uintptr_t len; } DeviceBuffer;
typedef struct VirtioMmio VirtioMmio;

// The typed kernel entry points (tests/qemu/tls/tls_demo.mc).
uint32_t tls_net_up(volatile VirtioMmio *regs, Virtq *rxq, Virtq *txq, uintptr_t rxbuf, uintptr_t rxmax);
uint32_t tls_resolve(uint32_t dns_ip);
uint32_t tls_resolved_ip(void);
uint32_t tls_connect(uint32_t dst_ip, uint16_t dst_port);
uint32_t tls_send(uintptr_t src, uintptr_t len);
uint32_t tls_recv(uintptr_t dst, uintptr_t max);
void tls_host_reset(void);
void tls_host_push(uint8_t c);

// One Ethernet-MTU scratch RX region the MC transport receives frames into.
static uint8_t framebuf[2048];

// ----- std/dma platform primitives: a bump allocator over one DMA pool -----
static uint8_t g_dma_pool[8u << 20] __attribute__((aligned(16))); // 8 MiB
static uintptr_t g_dma_off = 0;
uintptr_t mc_dma_alloc_base(uintptr_t len) {
    uintptr_t a = (len + 15u) & ~(uintptr_t)15u;
    if (g_dma_off + a > sizeof(g_dma_pool)) { for (;;) { } }
    uint8_t *p = g_dma_pool + g_dma_off;
    g_dma_off += a;
    for (uintptr_t i = 0; i < len; ++i) p[i] = 0;
    return (uintptr_t)p;
}
void mc_dma_free_base(uintptr_t a, uintptr_t b, uintptr_t c) { (void)a; (void)b; (void)c; }
void mc_dma_clean_for_device_base(uintptr_t a, uintptr_t b, uintptr_t c) { (void)a; (void)b; (void)c; }
uintptr_t mc_dma_invalidate_for_cpu_base(uintptr_t a, uintptr_t len) { (void)len; return a; }

// ----- UART (QEMU virt 16550 at 0x1000_0000) -----
#define UART ((volatile uint8_t *)0x10000000UL)
static void putc_(char c) { *UART = (uint8_t)c; }
static void puts_(const char *s) { for (; *s; ++s) putc_(*s); }
static void puthex(uint64_t v) {
    putc_('0'); putc_('x');
    for (int i = 60; i >= 0; i -= 4) putc_("0123456789abcdef"[(v >> i) & 0xf]);
}
static void puthex16(uint16_t v) {
    putc_('0'); putc_('x');
    for (int i = 12; i >= 0; i -= 4) putc_("0123456789abcdef"[(v >> i) & 0xf]);
}
static void put_ip(uint32_t ip) {
    for (int s = 24; s >= 0; s -= 8) {
        uint32_t o = (ip >> s) & 0xff;
        char tmp[3]; int n = 0;
        if (o == 0) putc_('0');
        else { while (o) { tmp[n++] = (char)('0' + (o % 10)); o /= 10; } while (n) putc_(tmp[--n]); }
        if (s) putc_('.');
    }
}

#define FINISHER ((volatile uint32_t *)0x00100000UL)
#define VIRTIO_MMIO_BASE 0x10001000UL
#define VIRTIO_MMIO_STRIDE 0x1000UL
#define VIRTIO_MMIO_COUNT 8

// ===================================================================== virtio-rng
// The virtio-rng (device-id 4) driver used to seed BearSSL's PRNG now lives in the
// shared kernel/drivers/virtio/virtio_rng.c (linked in by the test script), so the
// two former inline copies (here + bearssl_smoke_runtime.c) are one. It depends on
// mc_read_ticks() above; vrng_fill() copies device bytes into the caller's buffer.
#include "virtio_rng.h"

// ===================================================================== net device
static DescTable  g_rx_desc  __attribute__((aligned(16)));
static VringAvail g_rx_avail __attribute__((aligned(2)));
static VringUsed  g_rx_used  __attribute__((aligned(4)));
static DescTable  g_tx_desc  __attribute__((aligned(16)));
static VringAvail g_tx_avail __attribute__((aligned(2)));
static VringUsed  g_tx_used  __attribute__((aligned(4)));

static volatile VirtioMmio *find_net_device(void) {
    for (int i = 0; i < VIRTIO_MMIO_COUNT; ++i) {
        volatile uint32_t *slot = (volatile uint32_t *)(VIRTIO_MMIO_BASE + (uintptr_t)i * VIRTIO_MMIO_STRIDE);
        if (slot[0] == 0x74726976u && slot[2] == 1u) return (volatile VirtioMmio *)slot;
    }
    return 0;
}

// ===================================================================== THE BRIDGE
// BearSSL low-level transport callbacks. Each forwards to the MC TCP primitive; the
// MC side owns the sequence accounting + ACKing. Return -1 on the MC error sentinel.
static int low_write(void *ctx, const unsigned char *buf, size_t len) {
    (void)ctx;
    // Cap each segment at a conservative MSS so one segment carries the whole write.
    size_t chunk = len > 1400 ? 1400 : len;
    uint32_t n = tls_send((uintptr_t)buf, (uintptr_t)chunk);
    if (n == 0xFFFFFFFFu) return -1;
    return (int)n;
}
static int low_read(void *ctx, unsigned char *buf, size_t len) {
    (void)ctx;
    uint32_t n = tls_recv((uintptr_t)buf, (uintptr_t)len);
#ifdef TLS_DEBUG
    puts_("[low_read n="); puthex(n); puts_("]\n");
#endif
    if (n == 0xFFFFFFFFu) return -1;  // error/timeout
    if (n == 0) return -1;            // peer FIN -> BearSSL treats the read as failed
    return (int)n;
}

// ===================================================================== the request
// Build "GET / HTTP/1.1\r\nHost: <TLS_HOSTHDR>\r\nConnection: close\r\n\r\n".
static unsigned char g_req[256];
static size_t build_request(void) {
    const char *a = "GET / HTTP/1.1\r\nHost: ";
    const char *h = TLS_HOSTHDR;
    const char *b = "\r\nConnection: close\r\n\r\n";
    size_t n = 0;
    for (const char *p = a; *p; ++p) g_req[n++] = (unsigned char)*p;
    for (const char *p = h; *p; ++p) g_req[n++] = (unsigned char)*p;
    for (const char *p = b; *p; ++p) g_req[n++] = (unsigned char)*p;
    return n;
}

#define MC_XSTR(x) #x
#define MC_STR(x) MC_XSTR(x)

// The bidirectional TLS I/O buffer (allocated statically -- BR_SSL_BUFSIZE_BIDI).
static unsigned char g_iobuf[BR_SSL_BUFSIZE_BIDI];

__attribute__((used)) void test_main(void) {
    puts_("https-get booting\n");
    puts_("BUILD-EPOCH="); puthex(mc_build_epoch); putc_('\n');
    puts_("SERVER-NAME=" TLS_SERVERNAME "\n");

    volatile VirtioMmio *regs = find_net_device();
    if (!regs) { puts_("NODEV\n"); goto done; }

    // ---- entropy: pull >=32 bytes of real randomness from virtio-rng ----
    volatile uint8_t *rng = vrng_find();
    if (!rng || !vrng_init(rng)) { puts_("RNG-INIT-FAILED\n"); goto done; }
    unsigned char seed[64];
    uint32_t got = 0;
    while (got < 32) {
        uint8_t chunk[32];
        uint32_t k = vrng_fill(rng, chunk, 32);
        if (k == 0) { puts_("RNG-EMPTY\n"); goto done; }
        for (uint32_t i = 0; i < k && got < sizeof(seed); ++i) seed[got++] = chunk[i];
    }
    puts_("ENTROPY-OK len="); puthex(got); putc_('\n');

    // ---- bring the NIC up + ARP the gateway ----
    static Virtq rxq, txq;
    rxq.desc = &g_rx_desc; rxq.avail = &g_rx_avail; rxq.used = &g_rx_used;
    txq.desc = &g_tx_desc; txq.avail = &g_tx_avail; txq.used = &g_tx_used;
    if (!tls_net_up(regs, &rxq, &txq, (uintptr_t)framebuf, sizeof(framebuf))) {
        puts_("NIC-OR-ARP-FAILED\n"); goto done;
    }
    puts_("NET-UP\n");

    // ---- determine the target IP + port ----
    uint32_t dst_ip;
    uint16_t dst_port;
#ifdef TLS_GOOGLE
    // Resolve TLS_DNSHOST via DNS, connect to the real IP on :443.
    tls_host_reset();
    const char *dh = TLS_DNSHOST;
    puts_("resolving "); for (const char *p = dh; *p; ++p) { putc_(*p); tls_host_push((uint8_t)*p); }
    puts_(" via "); put_ip((uint32_t)DNS_SERVER_IP); putc_('\n');
    dst_ip = tls_resolve((uint32_t)DNS_SERVER_IP);
    if (dst_ip == 0) { puts_("DNS-NO-RESPONSE\n"); goto done; }
    puts_("RESOLVED-IP="); puthex(dst_ip); puts_(" ("); put_ip(dst_ip); puts_(")\n");
    dst_port = 443;
#else
    dst_ip = LOCAL_IP;       // 10.0.2.2 -> host loopback (python HTTPS server)
    dst_port = HTTPS_PORT;
    puts_("target="); put_ip(dst_ip); puts_(" port="); puthex(dst_port); putc_('\n');
#endif

    // ---- TCP active-open ----
    if (!tls_connect(dst_ip, dst_port)) { puts_("NO-SYN-ACK\n"); goto done; }
    puts_("TCP-CONNECTED\n");

    // ---- set up the REAL BearSSL TLS 1.2 client ----
    br_ssl_client_context cc;
    br_x509_minimal_context xc;
    br_ssl_client_init_full(&cc, &xc, TAs, TAs_NUM);
    br_ssl_engine_set_buffer(&cc.eng, g_iobuf, sizeof(g_iobuf), 1);

    // Inject the live entropy BEFORE reset (else the engine has no PRNG).
    br_ssl_engine_inject_entropy(&cc.eng, seed, got);

    // Set the X.509 validation time from the REAL goldfish-RTC wall clock (PRIMARY).
    // Fall back to the build epoch only if the RTC reads back an implausible "now"
    // (device absent/unpopulated). BearSSL day/second convention.
    uint64_t epoch = time_now_epoch();
    if (epoch < 1700000000ull || epoch >= 2000000000ull) {
        puts_("RTC-IMPLAUSIBLE-USING-BUILD-EPOCH\n");
        epoch = mc_build_epoch;
    } else {
        puts_("X509-TIME-FROM-RTC="); puthex(epoch); putc_('\n');
    }
    uint32_t days = (uint32_t)(epoch / 86400u) + 719528u;
    uint32_t secs = (uint32_t)(epoch % 86400u);
    br_x509_minimal_set_time(&xc, days, secs);

    if (!br_ssl_client_reset(&cc, TLS_SERVERNAME, 0)) {
        puts_("CLIENT-RESET-FAILED\n"); goto done;
    }
    puts_("TLS-HANDSHAKE-START\n");

    br_sslio_context ioc;
    br_sslio_init(&ioc, &cc.eng, low_read, NULL, low_write, NULL);

    // ---- send the HTTPS GET (encrypted) ----
    size_t reqlen = build_request();
    if (br_sslio_write_all(&ioc, g_req, reqlen) != 0) {
        puts_("TLS-WRITE-FAILED err="); puthex(br_ssl_engine_last_error(&cc.eng)); putc_('\n');
        goto done;
    }
    if (br_sslio_flush(&ioc) != 0) {
        puts_("TLS-FLUSH-FAILED err="); puthex(br_ssl_engine_last_error(&cc.eng)); putc_('\n');
        goto done;
    }
    puts_("TLS-REQUEST-SENT\n");

    // The handshake has now completed (write forces it). The error indicator at this
    // point is the AUTHORITATIVE proof of certificate validation: br_ssl_client_init_full
    // installed the X.509-minimal validator with our trust anchor, so the engine refuses
    // to finish the handshake (and would already have a BR_ERR_X509_* code here) unless
    // the server's chain validated against the embedded TA and matched the server_name.
    int hs_err = br_ssl_engine_last_error(&cc.eng);
    puts_("HANDSHAKE-ERROR="); puthex(hs_err); putc_('\n');
    {
        br_ssl_session_parameters sp;
        br_ssl_engine_get_session_parameters(&cc.eng, &sp);
        puts_("TLS-VERSION="); puthex16(sp.version); putc_('\n');
        puts_("CIPHER-SUITE="); puthex16(sp.cipher_suite); putc_('\n');
    }
    // Handshake finished with no error => the real cert chain validated against our TA.
    if (hs_err == 0) {
        puts_("CERT-CHAIN-VALIDATED\n");
    }

    // ---- read the decrypted response ----
    puts_("RESP-BEGIN\n");
    size_t total = 0;
    for (;;) {
        unsigned char tmp[512];
        int rd = br_sslio_read(&ioc, tmp, sizeof(tmp));
        if (rd <= 0) break;          // EOF, clean close, or error
        for (int i = 0; i < rd; ++i) putc_((char)tmp[i]);
        total += (size_t)rd;
        if (total > 8192) break;     // enough proof; stop reading
    }
    puts_("\nRESP-END\n");
    puts_("RESP-TOTAL="); puthex(total); putc_('\n');

    // After the body, the read terminates either on a clean TLS close (close_notify ->
    // engine CLOSED with last_error OK) or on the peer dropping TCP after the response
    // (a benign BR_ERR_IO over our minimal TCP). Report both honestly.
    unsigned st = br_ssl_engine_current_state(&cc.eng);
    int err = br_ssl_engine_last_error(&cc.eng);
    puts_("LAST-ERROR="); puthex(err); putc_('\n');
    if (st & BR_SSL_CLOSED) puts_("TLS-CLOSED-CLEAN\n");

    // Success criterion (honest): the handshake validated the cert chain against our TA
    // AND we decrypted real application data. A trailing BR_ERR_IO from the peer's abrupt
    // TCP close after a full response does not negate a real, validated TLS exchange.
    if (hs_err == 0 && total > 0) {
        puts_("HTTPS-GET-OK\n");
    } else if (total > 0) {
        puts_("HTTPS-PARTIAL (data received but handshake error "); puthex(hs_err); puts_(")\n");
    } else {
        puts_("HTTPS-NO-DATA\n");
    }

done:
    *FINISHER = 0x5555;
    for (;;) { }
}

__attribute__((naked, section(".text.start"))) void _start(void) {
    __asm__ volatile(
        "la sp, _stack_top\n"
        "call test_main\n"
        "1: j 1b\n");
}
