#!/usr/bin/env python3
"""Check golden first-line diagnostics for the checked bad fixture corpora."""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


PRIMARY_DIAG_RE = re.compile(r"^.+?:\d+:\d+:\s+error:\s+.*$")
EXPECT_RE = re.compile(r"EXPECT:\s+(E_[A-Z0-9_]+)")


@dataclass(frozen=True)
class Fixture:
    command: str
    path: Path


EMIT_LLVM_BAD_FIXTURES = (
    "tests/llvm/bad/unsupported_opaque_asm_operands_after_supported_stmt.mc",
    "tests/c_emit/bad/export_struct_param_by_value.mc",
    "tests/c_emit/bad/export_struct_return_by_value.mc",
    "tests/c_emit/bad/extern_struct_param_by_value.mc",
    "tests/c_emit/bad/extern_struct_return_by_value.mc",
)


ASYNC_CHECK_BAD_FIXTURES = (
    "tests/c_emit/bad/async_await_unresolved_dyn.mc",
    "tests/c_emit/bad/async_borrow_across_await.mc",
    "tests/c_emit/bad/async_borrow_pinning.mc",
    "tests/c_emit/bad/async_for_await_nested.mc",
)


def fixture_plan(root: Path) -> list[Fixture]:
    specs: list[Fixture] = []
    for pattern, command in (
        ("tests/c_emit/bad/*.mc", "emit-c"),
        ("demo/bad/*.mc", "check"),
        ("kernel/bad/*.mc", "check"),
    ):
        for path in sorted(root.glob(pattern)):
            specs.append(Fixture(command=command, path=path.relative_to(root)))
    for fixture in ASYNC_CHECK_BAD_FIXTURES:
        specs.append(Fixture(command="check", path=Path(fixture)))
    for fixture in EMIT_LLVM_BAD_FIXTURES:
        specs.append(Fixture(command="emit-llvm", path=Path(fixture)))
    return specs


def expected_code(path: Path) -> str:
    match = EXPECT_RE.search(path.read_text(encoding="utf-8"))
    if not match:
        raise RuntimeError(f"{path}: missing EXPECT: E_CODE line")
    return match.group(1)


def expected_primary_diagnostic(output: str, expected: str) -> str:
    for line in output.splitlines():
        if PRIMARY_DIAG_RE.match(line) and expected in line:
            marker = f"{expected}: "
            if marker not in line or not line.split(marker, 1)[1].strip():
                raise RuntimeError(f"primary diagnostic for {expected} has no locked wording:\n{line}")
            return line
    raise RuntimeError(f"no primary diagnostic line containing {expected} found in output:\n{output}")


def collect(root: Path, mcc: str) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for fixture in fixture_plan(root):
        path = root / fixture.path
        want = expected_code(path)
        proc = subprocess.run(
            [mcc, fixture.command, fixture.path.as_posix()],
            cwd=root,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        output = proc.stdout + proc.stderr
        if proc.returncode == 0:
            raise RuntimeError(f"{fixture.path}: expected rejection with {want}, but command succeeded")
        diag = expected_primary_diagnostic(output, want)
        rows.append((fixture.command, fixture.path.as_posix(), want, diag))
    return rows


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Generated by: python3 tools/toolchain/bad-diagnostics-test.py --write",
        "# command\tfixture\texpected_code\tfirst_primary_diagnostic_with_expected_code",
    ]
    for row in rows:
        lines.append("\t".join(row))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mcc", default="zig-out/bin/mcc", help="compiler binary to run")
    parser.add_argument("--write", action="store_true", help="rewrite the golden TSV")
    parser.add_argument("--check", action="store_true", help="check the golden TSV")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    target = root / "tests" / "diagnostics" / "bad-golden.tsv"
    try:
        generated = render(collect(root, args.mcc))
    except RuntimeError as err:
        print(f"FAIL: bad-diagnostics-test — {err}", file=sys.stderr)
        return 1

    if args.write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding="utf-8")
        return 0

    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(),
                generated.splitlines(),
                fromfile=str(target),
                tofile="generated",
                lineterm="",
            )
            print("\n".join(diff), file=sys.stderr)
            print("FAIL: bad-diagnostics-test — golden diagnostics changed; rerun with --write after reviewing wording", file=sys.stderr)
            return 1
        print(f"PASS: bad-diagnostics-test — {len(fixture_plan(root))} bad fixtures match golden diagnostics")
        return 0

    print(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
