#!/usr/bin/env sh
set -eu

MCC="${1:?usage: llvm-test.sh path/to/mcc}"
OUT_DIR="${2:-zig-out/llvm-test}"

mkdir -p "$OUT_DIR"
"$MCC" emit-llvm tests/c_emit/smoke.mc > "$OUT_DIR/smoke.ll"
llvm-as "$OUT_DIR/smoke.ll" -o "$OUT_DIR/smoke.bc"
"$MCC" emit-llvm tests/llvm/bool_switch.mc > "$OUT_DIR/bool_switch.ll"
llvm-as "$OUT_DIR/bool_switch.ll" -o "$OUT_DIR/bool_switch.bc"
"$MCC" emit-llvm tests/llvm/loops.mc > "$OUT_DIR/loops.ll"
llvm-as "$OUT_DIR/loops.ll" -o "$OUT_DIR/loops.bc"
"$MCC" emit-llvm tests/llvm/div_rem.mc > "$OUT_DIR/div_rem.ll"
llvm-as "$OUT_DIR/div_rem.ll" -o "$OUT_DIR/div_rem.bc"
"$MCC" emit-llvm tests/llvm/joins.mc > "$OUT_DIR/joins.ll"
llvm-as "$OUT_DIR/joins.ll" -o "$OUT_DIR/joins.bc"
"$MCC" emit-llvm tests/llvm/pointers.mc > "$OUT_DIR/pointers.ll"
llvm-as "$OUT_DIR/pointers.ll" -o "$OUT_DIR/pointers.bc"
"$MCC" emit-llvm tests/llvm/globals.mc > "$OUT_DIR/globals.ll"
llvm-as "$OUT_DIR/globals.ll" -o "$OUT_DIR/globals.bc"
"$MCC" emit-llvm tests/llvm/arrays.mc > "$OUT_DIR/arrays.ll"
llvm-as "$OUT_DIR/arrays.ll" -o "$OUT_DIR/arrays.bc"
"$MCC" emit-llvm tests/llvm/structs.mc > "$OUT_DIR/structs.ll"
llvm-as "$OUT_DIR/structs.ll" -o "$OUT_DIR/structs.bc"
"$MCC" emit-llvm tests/llvm/aggregate_globals.mc > "$OUT_DIR/aggregate_globals.ll"
llvm-as "$OUT_DIR/aggregate_globals.ll" -o "$OUT_DIR/aggregate_globals.bc"
"$MCC" emit-llvm tests/llvm/aggregate_abi.mc > "$OUT_DIR/aggregate_abi.ll"
llvm-as "$OUT_DIR/aggregate_abi.ll" -o "$OUT_DIR/aggregate_abi.bc"
"$MCC" emit-llvm tests/llvm/nested_aggregates.mc > "$OUT_DIR/nested_aggregates.ll"
llvm-as "$OUT_DIR/nested_aggregates.ll" -o "$OUT_DIR/nested_aggregates.bc"
"$MCC" emit-llvm tests/llvm/slices.mc > "$OUT_DIR/slices.ll"
llvm-as "$OUT_DIR/slices.ll" -o "$OUT_DIR/slices.bc"
"$MCC" emit-llvm tests/llvm/scalar_switch.mc > "$OUT_DIR/scalar_switch.ll"
llvm-as "$OUT_DIR/scalar_switch.ll" -o "$OUT_DIR/scalar_switch.bc"
"$MCC" emit-llvm tests/llvm/for_loops.mc > "$OUT_DIR/for_loops.ll"
llvm-as "$OUT_DIR/for_loops.ll" -o "$OUT_DIR/for_loops.bc"
"$MCC" emit-llvm tests/llvm/scalar_expressions.mc > "$OUT_DIR/scalar_expressions.ll"
llvm-as "$OUT_DIR/scalar_expressions.ll" -o "$OUT_DIR/scalar_expressions.bc"
"$MCC" emit-llvm tests/llvm/statement_workflow.mc > "$OUT_DIR/statement_workflow.ll"
llvm-as "$OUT_DIR/statement_workflow.ll" -o "$OUT_DIR/statement_workflow.bc"
"$MCC" emit-llvm tests/llvm/aggregate_rvalues.mc > "$OUT_DIR/aggregate_rvalues.ll"
llvm-as "$OUT_DIR/aggregate_rvalues.ll" -o "$OUT_DIR/aggregate_rvalues.bc"
"$MCC" emit-llvm tests/llvm/bool_conditions.mc > "$OUT_DIR/bool_conditions.ll"
llvm-as "$OUT_DIR/bool_conditions.ll" -o "$OUT_DIR/bool_conditions.bc"
"$MCC" emit-llvm tests/llvm/floats.mc > "$OUT_DIR/floats.ll"
llvm-as "$OUT_DIR/floats.ll" -o "$OUT_DIR/floats.bc"
"$MCC" emit-llvm tests/llvm/trap_never.mc > "$OUT_DIR/trap_never.ll"
llvm-as "$OUT_DIR/trap_never.ll" -o "$OUT_DIR/trap_never.bc"
"$MCC" emit-llvm tests/llvm/unsafe_machine_ops.mc > "$OUT_DIR/unsafe_machine_ops.ll"
llvm-as "$OUT_DIR/unsafe_machine_ops.ll" -o "$OUT_DIR/unsafe_machine_ops.bc"
"$MCC" emit-llvm tests/llvm/enums_aliases.mc > "$OUT_DIR/enums_aliases.ll"
llvm-as "$OUT_DIR/enums_aliases.ll" -o "$OUT_DIR/enums_aliases.bc"
"$MCC" emit-llvm tests/llvm/nullable_pointers.mc > "$OUT_DIR/nullable_pointers.ll"
llvm-as "$OUT_DIR/nullable_pointers.ll" -o "$OUT_DIR/nullable_pointers.bc"
"$MCC" emit-llvm tests/llvm/atomics.mc > "$OUT_DIR/atomics.ll"
llvm-as "$OUT_DIR/atomics.ll" -o "$OUT_DIR/atomics.bc"
"$MCC" emit-llvm tests/llvm/fn_pointers.mc > "$OUT_DIR/fn_pointers.ll"
llvm-as "$OUT_DIR/fn_pointers.ll" -o "$OUT_DIR/fn_pointers.bc"
"$MCC" emit-llvm tests/llvm/aggregate_assignments.mc > "$OUT_DIR/aggregate_assignments.ll"
llvm-as "$OUT_DIR/aggregate_assignments.ll" -o "$OUT_DIR/aggregate_assignments.bc"

grep -q '@llvm.uadd.with.overflow.i32' "$OUT_DIR/smoke.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/smoke.ll"
! grep -q ' nsw ' "$OUT_DIR/smoke.ll"
! grep -q ' nuw ' "$OUT_DIR/smoke.ll"
grep -q 'switch i1 %flag' "$OUT_DIR/bool_switch.ll"
grep -q 'call void @mc_trap_InvalidRepresentation()' "$OUT_DIR/bool_switch.ll"
grep -q 'icmp ugt i32 %x, 10' "$OUT_DIR/bool_switch.ll"
grep -q 'alloca i32' "$OUT_DIR/loops.ll"
grep -q 'store i32' "$OUT_DIR/loops.ll"
grep -q 'load i32' "$OUT_DIR/loops.ll"
grep -q 'br label %while_cond' "$OUT_DIR/loops.ll"
grep -q '@llvm.usub.with.overflow.i32' "$OUT_DIR/loops.ll"
grep -q 'call void @mc_trap_DivideByZero()' "$OUT_DIR/div_rem.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/div_rem.ll"
grep -q 'sdiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'srem i32' "$OUT_DIR/div_rem.ll"
grep -q 'udiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'urem i32' "$OUT_DIR/div_rem.ll"
grep -q 'switch_end' "$OUT_DIR/joins.ll"
grep -q 'br label %switch_end' "$OUT_DIR/joins.ll"
grep -q 'store i32' "$OUT_DIR/joins.ll"
grep -q 'define i32 @load_ptr(ptr %p)' "$OUT_DIR/pointers.ll"
grep -q 'load i32, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store i32 %value, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store ptr %x.addr, ptr %p.addr' "$OUT_DIR/pointers.ll"
grep -q '@shared = global i32 7' "$OUT_DIR/globals.ll"
grep -q '@flag = global i1 0' "$OUT_DIR/globals.ll"
grep -q '@shared_ptr = global ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'load i32, ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'store i32 %value, ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'alloca \[2 x i32\]' "$OUT_DIR/arrays.ll"
grep -q 'getelementptr inbounds \[2 x i32\]' "$OUT_DIR/arrays.ll"
grep -q 'call void @mc_trap_Bounds()' "$OUT_DIR/arrays.ll"
grep -q 'store ptr %t' "$OUT_DIR/arrays.ll"
grep -q 'alloca { i32, i32 }' "$OUT_DIR/structs.ll"
grep -q 'getelementptr inbounds { i32, i32 }' "$OUT_DIR/structs.ll"
grep -q 'store i32 %value, ptr %t' "$OUT_DIR/structs.ll"
grep -q 'store ptr %t' "$OUT_DIR/structs.ll"
grep -q '@values = global \[2 x i32\] \[i32 10, i32 20\]' "$OUT_DIR/aggregate_globals.ll"
grep -q '@pair = global { i32, i32 } { i32 1, i32 2 }' "$OUT_DIR/aggregate_globals.ll"
grep -q 'getelementptr inbounds \[2 x i32\], ptr @values' "$OUT_DIR/aggregate_globals.ll"
grep -q 'getelementptr inbounds { i32, i32 }, ptr @pair' "$OUT_DIR/aggregate_globals.ll"
grep -q 'define { i32, i32 } @make_pair()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'define i32 @take_pair({ i32, i32 } %pair)' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call { i32, i32 } @make_pair()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call i32 @take_pair({ i32, i32 }' "$OUT_DIR/aggregate_abi.ll"
grep -q 'define \[2 x i32\] @make_row()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call i32 @take_row(\[2 x i32\]' "$OUT_DIR/aggregate_abi.ll"
grep -q '@matrix = global \[2 x \[2 x i32\]\]' "$OUT_DIR/nested_aggregates.ll"
grep -q '@box = global { { i32, i32 } }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds \[2 x \[2 x i32\]\]' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds { { i32, i32 } }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds { i32, i32 }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'declare { ptr, i64 } @make_u8_slice()' "$OUT_DIR/slices.ll"
grep -q 'define i8 @read_slice({ ptr, i64 } %xs, i64 %i)' "$OUT_DIR/slices.ll"
grep -q 'define { ptr, i64 } @same_slice({ ptr, i64 } %xs)' "$OUT_DIR/slices.ll"
grep -q 'extractvalue { ptr, i64 }' "$OUT_DIR/slices.ll"
grep -q 'insertvalue { ptr, i64 } undef, ptr' "$OUT_DIR/slices.ll"
grep -q 'getelementptr inbounds i8, ptr' "$OUT_DIR/slices.ll"
grep -q 'icmp ule i64' "$OUT_DIR/slices.ll"
grep -q 'switch i32 %n' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 1, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 2, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'switch i8 %c' "$OUT_DIR/scalar_switch.ll"
grep -q 'i8 65, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i8 10, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'switch i32 %n, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 -1, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'br label %for_cond' "$OUT_DIR/for_loops.ll"
grep -q 'for_body' "$OUT_DIR/for_loops.ll"
grep -q 'for_step' "$OUT_DIR/for_loops.ll"
grep -q 'for_end' "$OUT_DIR/for_loops.ll"
grep -q 'getelementptr inbounds i32, ptr' "$OUT_DIR/for_loops.ll"
grep -q 'getelementptr inbounds \[4 x i32\]' "$OUT_DIR/for_loops.ll"
grep -q 'call { ptr, i64 } @make_u32_slice()' "$OUT_DIR/for_loops.ll"
grep -q 'br label %while_end' "$OUT_DIR/for_loops.ll"
grep -q 'br label %while_cond' "$OUT_DIR/for_loops.ll"
grep -q ' and i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q ' or i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q ' xor i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q 'shl i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'lshr i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'zext i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'trunc i64' "$OUT_DIR/scalar_expressions.ll"
grep -q 'call void @mc_trap_InvalidShift()' "$OUT_DIR/scalar_expressions.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/scalar_expressions.ll"
grep -q 'declare void @consume_u32(i32)' "$OUT_DIR/statement_workflow.ll"
grep -q 'call void @consume_u32(i32 %value)' "$OUT_DIR/statement_workflow.ll"
grep -q 'call i32 @combine(i32 %left, i32 %right)' "$OUT_DIR/statement_workflow.ll"
grep -q 'load i32, ptr %out.addr' "$OUT_DIR/statement_workflow.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/statement_workflow.ll"
grep -q 'call \[4 x i32\] @make_values(i32 %seed)' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'call { \[4 x i32\], { ptr, i64 } } @make_bag(i32 %seed)' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'store \[4 x i32\] %t' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'store { \[4 x i32\], { ptr, i64 } } %t' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'getelementptr inbounds \[4 x i32\]' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'extractvalue { ptr, i64 }' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'for_body' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'declare void @mc_trap_Assert()' "$OUT_DIR/bool_conditions.ll"
grep -q 'logic_and_rhs' "$OUT_DIR/bool_conditions.ll"
grep -q 'logic_or_rhs' "$OUT_DIR/bool_conditions.ll"
grep -q 'call void @mc_trap_Assert()' "$OUT_DIR/bool_conditions.ll"
grep -q 'call i32 @next_value()' "$OUT_DIR/bool_conditions.ll"
grep -q 'call void @consume_bool(i1' "$OUT_DIR/bool_conditions.ll"
grep -q '@gain = global float 1.5' "$OUT_DIR/floats.ll"
grep -q '@bias = global double -0.25' "$OUT_DIR/floats.ll"
grep -q 'fadd float' "$OUT_DIR/floats.ll"
grep -q 'fsub double' "$OUT_DIR/floats.ll"
grep -q 'fmul float' "$OUT_DIR/floats.ll"
grep -q 'fdiv double' "$OUT_DIR/floats.ll"
grep -q 'fcmp olt float' "$OUT_DIR/floats.ll"
grep -q 'fcmp une double' "$OUT_DIR/floats.ll"
grep -q 'fneg double' "$OUT_DIR/floats.ll"
grep -q 'declare void @mc_trap_Unreachable()' "$OUT_DIR/trap_never.ll"
grep -q 'define i32 @trap_as_value()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Bounds()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Unreachable()' "$OUT_DIR/trap_never.ll"
grep -q 'define void @never_returns_by_trap()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Assert()' "$OUT_DIR/trap_never.ll"
grep -q 'ret void' "$OUT_DIR/trap_never.ll"
grep -q 'define i32 @read_u32(i64 %addr)' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'inttoptr i64' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'load volatile i32' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'store volatile i32' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'call void asm sideeffect "pause", "~{memory}"()' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'getelementptr inbounds i8' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'define ptr @offset_address' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q '@default_error = global i64 1' "$OUT_DIR/enums_aliases.ll"
grep -q '@default_errors = global \[2 x i64\] \[i64 0, i64 2\]' "$OUT_DIR/enums_aliases.ll"
grep -q '@counts = global \[3 x i32\] \[i32 1, i32 2, i32 3\]' "$OUT_DIR/enums_aliases.ll"
grep -q '@llvm.uadd.with.overflow.i32' "$OUT_DIR/enums_aliases.ll"
grep -q 'define i8 @open_enum_raw(i8 %state)' "$OUT_DIR/enums_aliases.ll"
grep -q 'ret i8 -1' "$OUT_DIR/enums_aliases.ll"
grep -q 'ret i8 65' "$OUT_DIR/enums_aliases.ll"
grep -q 'switch i8 %irq' "$OUT_DIR/enums_aliases.ll"
grep -q 'switch i64 %error' "$OUT_DIR/enums_aliases.ll"
grep -q 'call void @mc_trap_InvalidRepresentation()' "$OUT_DIR/enums_aliases.ll"
grep -q 'define ptr @alias_raw_offset' "$OUT_DIR/enums_aliases.ll"
grep -q 'declare void @mc_trap_NullUnwrap()' "$OUT_DIR/nullable_pointers.ll"
grep -q '@saved_nullable = global ptr null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define ptr @nullable_null()' "$OUT_DIR/nullable_pointers.ll"
grep -q 'ret ptr null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'icmp eq ptr %maybe, null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'call void @mc_trap_NullUnwrap()' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define ptr @unwrap_or(ptr %maybe, ptr %fallback)' "$OUT_DIR/nullable_pointers.ll"
grep -q 'nullable_some' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define i32 @nullable_switch(ptr %maybe)' "$OUT_DIR/nullable_pointers.ll"
grep -q 'call ptr @maybe_ptr_from' "$OUT_DIR/nullable_pointers.ll"
grep -q '@ticks = global i32 0' "$OUT_DIR/atomics.ll"
grep -q 'load atomic i8, ptr .* acquire, align 1' "$OUT_DIR/atomics.ll"
grep -q 'trunc i8 .* to i1' "$OUT_DIR/atomics.ll"
grep -q 'zext i1 %value to i8' "$OUT_DIR/atomics.ll"
grep -q 'store atomic i8 .* ptr .* release, align 1' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr .* i64 %delta acq_rel' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw sub ptr .* i32 %delta release' "$OUT_DIR/atomics.ll"
grep -q 'monotonic, align 1' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr .* i32 %delta seq_cst' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr @ticks, i32 1 acq_rel' "$OUT_DIR/atomics.ll"
grep -q 'load atomic i32, ptr @ticks acquire, align 4' "$OUT_DIR/atomics.ll"
grep -q 'store atomic i32 0, ptr @ticks release, align 4' "$OUT_DIR/atomics.ll"
grep -q '@default_op = global ptr @add' "$OUT_DIR/fn_pointers.ll"
grep -q '@default_ops = global \[2 x ptr\] \[ptr @add, ptr @mul\]' "$OUT_DIR/fn_pointers.ll"
grep -q '@default_box = global { ptr } { ptr @add }' "$OUT_DIR/fn_pointers.ll"
grep -q 'define i32 @apply(ptr %op, i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q 'call i32 %op(i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q 'ret ptr @tick' "$OUT_DIR/fn_pointers.ll"
grep -q 'load ptr, ptr @default_op' "$OUT_DIR/fn_pointers.ll"
grep -q 'getelementptr inbounds \[2 x ptr\], ptr @default_ops' "$OUT_DIR/fn_pointers.ll"
grep -q 'getelementptr inbounds { ptr }, ptr %o, i64 0, i32 0' "$OUT_DIR/fn_pointers.ll"
grep -q 'call i32 @dispatch(ptr %op.addr, i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q 'define \[2 x i32\] @assign_array_literal()' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'alloca \[2 x i32\]' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'store \[2 x i32\] %t' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'store { i32, i32 } %t' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds \[2 x \[2 x i32\]\], ptr @matrix' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds { \[2 x \[2 x i32\]\] }, ptr @box' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds \[2 x { \[2 x i32\] }\], ptr @row_boxes' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'call i32 @consume_row(\[2 x i32\]' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'call i32 @consume_pair({ i32, i32 }' "$OUT_DIR/aggregate_assignments.ll"
