#!/usr/bin/env sh
set -eu

if [ "$#" -gt 0 ]; then
    if [ -z "$1" ]; then
        echo "usage: llvm-obj-test.sh path/to/mcc" >&2
        exit 1
    fi
    MCC="$1"
elif [ -n "${MCC_UNDER_TEST:-}" ]; then
    MCC="$MCC_UNDER_TEST"
else
    echo "usage: llvm-obj-test.sh path/to/mcc" >&2
    exit 1
fi
OUT_DIR="${2:-zig-out/llvm-obj-test}"

command -v llc >/dev/null 2>&1 || { echo "SKIP: llvm-obj-test (llc not found)"; exit 0; }
command -v nm >/dev/null 2>&1 || { echo "SKIP: llvm-obj-test (nm not found)"; exit 0; }

mkdir -p "$OUT_DIR"

# emit-llvm emits no target triple, so llc would inherit the host default (aarch64 in the
# arm64 dev container) and fail to assemble the precise-asm fixtures' inline asm. Pin one
# deterministic triple for every object (their valid asm is x86-64; all other fixtures emit
# target-neutral IR that assembles for it just as well).
objc() { MCC_UNDER_TEST="$MCC" MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh "$@" -mtriple=x86_64-unknown-none; }

objc tests/c_emit/smoke.mc -o "$OUT_DIR/smoke.o"
objc tests/llvm/scalar_expressions.mc -o "$OUT_DIR/scalar_expressions.o"
objc tests/c_emit/array_literals.mc -o "$OUT_DIR/array_literals.o"
objc tests/c_emit/arithmetic_checked.mc -o "$OUT_DIR/arithmetic_checked.o"
objc tests/c_emit/fixed_width_arithmetic.mc -o "$OUT_DIR/fixed_width_arithmetic.o"
objc tests/c_emit/checked_in_comparison.mc -o "$OUT_DIR/checked_in_comparison.o"
objc tests/c_emit/bitcast_aliasing.mc -o "$OUT_DIR/bitcast_aliasing.o"
objc tests/c_emit/byte_views.mc -o "$OUT_DIR/byte_views.o"
objc tests/c_emit/packed_overlay.mc -o "$OUT_DIR/packed_overlay.o"
objc tests/c_emit/packed_bits_overlay.mc -o "$OUT_DIR/packed_bits_overlay.o"
objc tests/c_emit/const_get.mc -o "$OUT_DIR/const_get.o"
objc tests/llvm/statement_workflow.mc -o "$OUT_DIR/statement_workflow.o"
objc tests/c_emit/comptime.mc -o "$OUT_DIR/comptime.o"
objc tests/llvm/aggregate_rvalues.mc -o "$OUT_DIR/aggregate_rvalues.o"
objc tests/llvm/bool_conditions.mc -o "$OUT_DIR/bool_conditions.o"
objc tests/c_emit/for_loops.mc -o "$OUT_DIR/for_loops_full.o"
objc tests/c_emit/slice_ranges.mc -o "$OUT_DIR/slice_ranges.o"
objc tests/c_emit/arrays_slices.mc -o "$OUT_DIR/arrays_slices.o"
objc tests/c_emit/pointer_views.mc -o "$OUT_DIR/pointer_views.o"
objc tests/c_emit/char_literals.mc -o "$OUT_DIR/char_literals.o"
objc tests/c_emit/string_literals.mc -o "$OUT_DIR/string_literals.o"
objc tests/c_emit/char_arithmetic.mc -o "$OUT_DIR/char_arithmetic.o"
objc tests/llvm/floats.mc -o "$OUT_DIR/floats.o"
objc tests/llvm/trap_never.mc -o "$OUT_DIR/trap_never.o"
objc tests/llvm/unsafe_machine_ops.mc -o "$OUT_DIR/unsafe_machine_ops.o"
objc tests/c_emit/asm.mc -o "$OUT_DIR/asm.o"
objc tests/c_emit/precise_asm.mc -o "$OUT_DIR/precise_asm.o"
objc tests/c_emit/unsafe_context.mc -o "$OUT_DIR/unsafe_context.o"
objc tests/c_emit/mmio.mc -o "$OUT_DIR/mmio.o"
objc tests/c_emit/mmio_offset.mc -o "$OUT_DIR/mmio_offset.o"
objc tests/c_emit/mmio_ordering.mc -o "$OUT_DIR/mmio_ordering.o"
objc tests/llvm/dma_irq_markers.mc -o "$OUT_DIR/dma_irq_markers.o"
objc tests/c_emit/irq_context.mc -o "$OUT_DIR/irq_context.o"
objc tests/c_emit/addr.mc -o "$OUT_DIR/addr.o"
objc tests/c_emit/address_classes.mc -o "$OUT_DIR/address_classes.o"
objc tests/c_emit/float_buffers.mc -o "$OUT_DIR/float_buffers.o"
objc tests/c_emit/vector_lanes.mc -o "$OUT_DIR/vector_lanes.o"
objc tests/llvm/enums_aliases.mc -o "$OUT_DIR/enums_aliases.o"
objc tests/c_emit/declarations.mc -o "$OUT_DIR/declarations.o"
objc tests/c_emit/assignment_values.mc -o "$OUT_DIR/assignment_values.o"
objc tests/c_emit/type_aliases.mc -o "$OUT_DIR/type_aliases.o"
objc tests/c_emit/enum_switch.mc -o "$OUT_DIR/enum_switch.o"
objc tests/llvm/nullable_pointers.mc -o "$OUT_DIR/nullable_pointers.o"
objc tests/llvm/aggregate_abi.mc -o "$OUT_DIR/aggregate_abi.o"
objc tests/c_emit/aggregate_ordering.mc -o "$OUT_DIR/aggregate_ordering.o"
objc tests/llvm/atomics.mc -o "$OUT_DIR/atomics.o"
objc tests/llvm/fn_pointers.mc -o "$OUT_DIR/fn_pointers.o"
objc tests/c_emit/fn_pointer.mc -o "$OUT_DIR/fn_pointer_full.o"
objc tests/llvm/aggregate_assignments.mc -o "$OUT_DIR/aggregate_assignments.o"
objc tests/c_emit/struct_literals.mc -o "$OUT_DIR/struct_literals.o"
objc tests/c_emit/array_values.mc -o "$OUT_DIR/array_values.o"
objc tests/c_emit/generic_structs.mc -o "$OUT_DIR/generic_structs.o"
objc tests/c_emit/monomorphize.mc -o "$OUT_DIR/monomorphize.o"
objc tests/c_emit/initialization.mc -o "$OUT_DIR/initialization.o"
objc tests/c_emit/result.mc -o "$OUT_DIR/result.o"
objc tests/c_emit/void_result.mc -o "$OUT_DIR/void_result.o"
objc tests/c_emit/if_let_narrowing.mc -o "$OUT_DIR/if_let_narrowing.o"
objc tests/c_emit/try_in_expressions.mc -o "$OUT_DIR/try_in_expressions.o"
objc tests/c_emit/try_propagation.mc -o "$OUT_DIR/try_propagation.o"
objc tests/c_emit/defer.mc -o "$OUT_DIR/defer.o"
objc tests/c_emit/defer_cleanup.mc -o "$OUT_DIR/defer_cleanup.o"
objc tests/c_emit/conversions.mc -o "$OUT_DIR/conversions.o"
objc tests/c_emit/arithmetic_domains.mc -o "$OUT_DIR/arithmetic_domains.o"
objc tests/c_emit/serial_counter.mc -o "$OUT_DIR/serial_counter.o"
objc tests/c_emit/library_results.mc -o "$OUT_DIR/library_results.o"
objc tests/c_emit/reduce_sum_checked.mc -o "$OUT_DIR/reduce_sum_checked.o"
objc tests/c_emit/wrapping_builtin.mc -o "$OUT_DIR/wrapping_builtin.o"
objc tests/c_emit/no_lang_trap.mc -o "$OUT_DIR/no_lang_trap.o"
objc tests/llvm/move_linear_valid.mc -o "$OUT_DIR/move_linear_valid.o"
objc tests/c_emit/unsafe_contract.mc -o "$OUT_DIR/unsafe_contract.o"
objc tests/c_emit/unsafe_contract_scope.mc -o "$OUT_DIR/unsafe_contract_scope.o"
objc tests/c_emit/tagged_union.mc -o "$OUT_DIR/tagged_union.o"
objc tests/c_emit/global_initializers.mc -o "$OUT_DIR/global_initializers.o"
objc tests/c_emit/reflection.mc -o "$OUT_DIR/reflection.o"
objc tests/c_emit/global_closure.mc -o "$OUT_DIR/global_closure.o"

test -s "$OUT_DIR/smoke.o"
test -s "$OUT_DIR/scalar_expressions.o"
test -s "$OUT_DIR/array_literals.o"
test -s "$OUT_DIR/arithmetic_checked.o"
test -s "$OUT_DIR/fixed_width_arithmetic.o"
test -s "$OUT_DIR/checked_in_comparison.o"
test -s "$OUT_DIR/bitcast_aliasing.o"
test -s "$OUT_DIR/byte_views.o"
test -s "$OUT_DIR/packed_overlay.o"
test -s "$OUT_DIR/packed_bits_overlay.o"
test -s "$OUT_DIR/const_get.o"
test -s "$OUT_DIR/statement_workflow.o"
test -s "$OUT_DIR/comptime.o"
test -s "$OUT_DIR/aggregate_rvalues.o"
test -s "$OUT_DIR/bool_conditions.o"
test -s "$OUT_DIR/for_loops_full.o"
test -s "$OUT_DIR/slice_ranges.o"
test -s "$OUT_DIR/arrays_slices.o"
test -s "$OUT_DIR/pointer_views.o"
test -s "$OUT_DIR/char_literals.o"
test -s "$OUT_DIR/string_literals.o"
test -s "$OUT_DIR/char_arithmetic.o"
test -s "$OUT_DIR/floats.o"
test -s "$OUT_DIR/trap_never.o"
test -s "$OUT_DIR/unsafe_machine_ops.o"
test -s "$OUT_DIR/asm.o"
test -s "$OUT_DIR/precise_asm.o"
test -s "$OUT_DIR/unsafe_context.o"
test -s "$OUT_DIR/mmio.o"
test -s "$OUT_DIR/mmio_offset.o"
test -s "$OUT_DIR/mmio_ordering.o"
test -s "$OUT_DIR/dma_irq_markers.o"
test -s "$OUT_DIR/irq_context.o"
test -s "$OUT_DIR/addr.o"
test -s "$OUT_DIR/address_classes.o"
test -s "$OUT_DIR/float_buffers.o"
test -s "$OUT_DIR/vector_lanes.o"
test -s "$OUT_DIR/enums_aliases.o"
test -s "$OUT_DIR/declarations.o"
test -s "$OUT_DIR/assignment_values.o"
test -s "$OUT_DIR/type_aliases.o"
test -s "$OUT_DIR/enum_switch.o"
test -s "$OUT_DIR/nullable_pointers.o"
test -s "$OUT_DIR/aggregate_abi.o"
test -s "$OUT_DIR/aggregate_ordering.o"
test -s "$OUT_DIR/atomics.o"
test -s "$OUT_DIR/fn_pointers.o"
test -s "$OUT_DIR/fn_pointer_full.o"
test -s "$OUT_DIR/aggregate_assignments.o"
test -s "$OUT_DIR/struct_literals.o"
test -s "$OUT_DIR/array_values.o"
test -s "$OUT_DIR/generic_structs.o"
test -s "$OUT_DIR/monomorphize.o"
test -s "$OUT_DIR/initialization.o"
test -s "$OUT_DIR/result.o"
test -s "$OUT_DIR/void_result.o"
test -s "$OUT_DIR/if_let_narrowing.o"
test -s "$OUT_DIR/try_in_expressions.o"
test -s "$OUT_DIR/try_propagation.o"
test -s "$OUT_DIR/defer.o"
test -s "$OUT_DIR/defer_cleanup.o"
test -s "$OUT_DIR/conversions.o"
test -s "$OUT_DIR/arithmetic_domains.o"
test -s "$OUT_DIR/serial_counter.o"
test -s "$OUT_DIR/library_results.o"
test -s "$OUT_DIR/reduce_sum_checked.o"
test -s "$OUT_DIR/wrapping_builtin.o"
test -s "$OUT_DIR/no_lang_trap.o"
test -s "$OUT_DIR/move_linear_valid.o"
test -s "$OUT_DIR/unsafe_contract.o"
test -s "$OUT_DIR/unsafe_contract_scope.o"
test -s "$OUT_DIR/tagged_union.o"
test -s "$OUT_DIR/global_initializers.o"
test -s "$OUT_DIR/reflection.o"
test -s "$OUT_DIR/global_closure.o"

nm "$OUT_DIR/smoke.o" > "$OUT_DIR/smoke.nm"
nm "$OUT_DIR/scalar_expressions.o" > "$OUT_DIR/scalar_expressions.nm"
nm "$OUT_DIR/array_literals.o" > "$OUT_DIR/array_literals.nm"
nm "$OUT_DIR/bitcast_aliasing.o" > "$OUT_DIR/bitcast_aliasing.nm"
nm "$OUT_DIR/byte_views.o" > "$OUT_DIR/byte_views.nm"
nm "$OUT_DIR/packed_overlay.o" > "$OUT_DIR/packed_overlay.nm"
nm "$OUT_DIR/packed_bits_overlay.o" > "$OUT_DIR/packed_bits_overlay.nm"
nm "$OUT_DIR/const_get.o" > "$OUT_DIR/const_get.nm"
nm "$OUT_DIR/statement_workflow.o" > "$OUT_DIR/statement_workflow.nm"
nm "$OUT_DIR/comptime.o" > "$OUT_DIR/comptime.nm"
nm "$OUT_DIR/aggregate_rvalues.o" > "$OUT_DIR/aggregate_rvalues.nm"
nm "$OUT_DIR/bool_conditions.o" > "$OUT_DIR/bool_conditions.nm"
nm "$OUT_DIR/for_loops_full.o" > "$OUT_DIR/for_loops_full.nm"
nm "$OUT_DIR/slice_ranges.o" > "$OUT_DIR/slice_ranges.nm"
nm "$OUT_DIR/arrays_slices.o" > "$OUT_DIR/arrays_slices.nm"
nm "$OUT_DIR/pointer_views.o" > "$OUT_DIR/pointer_views.nm"
nm "$OUT_DIR/string_literals.o" > "$OUT_DIR/string_literals.nm"
nm "$OUT_DIR/floats.o" > "$OUT_DIR/floats.nm"
nm "$OUT_DIR/trap_never.o" > "$OUT_DIR/trap_never.nm"
nm "$OUT_DIR/unsafe_machine_ops.o" > "$OUT_DIR/unsafe_machine_ops.nm"
nm "$OUT_DIR/asm.o" > "$OUT_DIR/asm.nm"
nm "$OUT_DIR/precise_asm.o" > "$OUT_DIR/precise_asm.nm"
nm "$OUT_DIR/unsafe_context.o" > "$OUT_DIR/unsafe_context.nm"
nm "$OUT_DIR/mmio.o" > "$OUT_DIR/mmio.nm"
nm "$OUT_DIR/mmio_offset.o" > "$OUT_DIR/mmio_offset.nm"
nm "$OUT_DIR/mmio_ordering.o" > "$OUT_DIR/mmio_ordering.nm"
nm "$OUT_DIR/dma_irq_markers.o" > "$OUT_DIR/dma_irq_markers.nm"
nm "$OUT_DIR/irq_context.o" > "$OUT_DIR/irq_context.nm"
nm "$OUT_DIR/addr.o" > "$OUT_DIR/addr.nm"
nm "$OUT_DIR/address_classes.o" > "$OUT_DIR/address_classes.nm"
nm "$OUT_DIR/float_buffers.o" > "$OUT_DIR/float_buffers.nm"
nm "$OUT_DIR/vector_lanes.o" > "$OUT_DIR/vector_lanes.nm"
nm "$OUT_DIR/enums_aliases.o" > "$OUT_DIR/enums_aliases.nm"
nm "$OUT_DIR/declarations.o" > "$OUT_DIR/declarations.nm"
nm "$OUT_DIR/assignment_values.o" > "$OUT_DIR/assignment_values.nm"
nm "$OUT_DIR/type_aliases.o" > "$OUT_DIR/type_aliases.nm"
nm "$OUT_DIR/enum_switch.o" > "$OUT_DIR/enum_switch.nm"
nm "$OUT_DIR/nullable_pointers.o" > "$OUT_DIR/nullable_pointers.nm"
nm "$OUT_DIR/aggregate_abi.o" > "$OUT_DIR/aggregate_abi.nm"
nm "$OUT_DIR/atomics.o" > "$OUT_DIR/atomics.nm"
nm "$OUT_DIR/fn_pointers.o" > "$OUT_DIR/fn_pointers.nm"
nm "$OUT_DIR/fn_pointer_full.o" > "$OUT_DIR/fn_pointer_full.nm"
nm "$OUT_DIR/aggregate_assignments.o" > "$OUT_DIR/aggregate_assignments.nm"
nm "$OUT_DIR/struct_literals.o" > "$OUT_DIR/struct_literals.nm"
nm "$OUT_DIR/array_values.o" > "$OUT_DIR/array_values.nm"
nm "$OUT_DIR/generic_structs.o" > "$OUT_DIR/generic_structs.nm"
nm "$OUT_DIR/monomorphize.o" > "$OUT_DIR/monomorphize.nm"
nm "$OUT_DIR/initialization.o" > "$OUT_DIR/initialization.nm"
nm "$OUT_DIR/result.o" > "$OUT_DIR/result.nm"
nm "$OUT_DIR/void_result.o" > "$OUT_DIR/void_result.nm"
nm "$OUT_DIR/if_let_narrowing.o" > "$OUT_DIR/if_let_narrowing.nm"
nm "$OUT_DIR/try_in_expressions.o" > "$OUT_DIR/try_in_expressions.nm"
nm "$OUT_DIR/try_propagation.o" > "$OUT_DIR/try_propagation.nm"
nm "$OUT_DIR/defer.o" > "$OUT_DIR/defer.nm"
nm "$OUT_DIR/defer_cleanup.o" > "$OUT_DIR/defer_cleanup.nm"
nm "$OUT_DIR/conversions.o" > "$OUT_DIR/conversions.nm"
nm "$OUT_DIR/arithmetic_domains.o" > "$OUT_DIR/arithmetic_domains.nm"
nm "$OUT_DIR/serial_counter.o" > "$OUT_DIR/serial_counter.nm"
nm "$OUT_DIR/library_results.o" > "$OUT_DIR/library_results.nm"
nm "$OUT_DIR/reduce_sum_checked.o" > "$OUT_DIR/reduce_sum_checked.nm"
nm "$OUT_DIR/wrapping_builtin.o" > "$OUT_DIR/wrapping_builtin.nm"
nm "$OUT_DIR/no_lang_trap.o" > "$OUT_DIR/no_lang_trap.nm"
nm "$OUT_DIR/unsafe_contract.o" > "$OUT_DIR/unsafe_contract.nm"
nm "$OUT_DIR/unsafe_contract_scope.o" > "$OUT_DIR/unsafe_contract_scope.nm"
nm "$OUT_DIR/tagged_union.o" > "$OUT_DIR/tagged_union.nm"
nm "$OUT_DIR/global_initializers.o" > "$OUT_DIR/global_initializers.nm"
nm "$OUT_DIR/reflection.o" > "$OUT_DIR/reflection.nm"
nm "$OUT_DIR/global_closure.o" > "$OUT_DIR/global_closure.nm"

grep -q ' add_one$' "$OUT_DIR/smoke.nm"
grep -q ' checked_left_shift$' "$OUT_DIR/scalar_expressions.nm"
grep -q ' flag_set$' "$OUT_DIR/scalar_expressions.nm"
grep -q ' reflected_const_length$' "$OUT_DIR/array_literals.nm"
grep -q ' reflected_field_offset_const_length$' "$OUT_DIR/array_literals.nm"
grep -q ' global_nested_array_row$' "$OUT_DIR/array_literals.nm"
grep -q ' bitcast_float_to_bits$' "$OUT_DIR/bitcast_aliasing.nm"
grep -q ' bitcast_bits_to_float$' "$OUT_DIR/bitcast_aliasing.nm"
grep -q ' as_bytes_index$' "$OUT_DIR/byte_views.nm"
grep -q ' bytes_equal_pair$' "$OUT_DIR/byte_views.nm"
grep -q ' bytes_equal_local_slices$' "$OUT_DIR/byte_views.nm"
grep -q ' set_tx_empty$' "$OUT_DIR/packed_overlay.nm"
grep -q ' update_global_tx_empty$' "$OUT_DIR/packed_overlay.nm"
grep -q ' set_word$' "$OUT_DIR/packed_overlay.nm"
grep -q ' first_byte$' "$OUT_DIR/packed_overlay.nm"
grep -q ' accept_overlay_reflection$' "$OUT_DIR/packed_bits_overlay.nm"
grep -q ' accept_packed_bits_literal_local$' "$OUT_DIR/packed_bits_overlay.nm"
grep -q ' pick_const$' "$OUT_DIR/const_get.nm"
grep -q ' pick_checked$' "$OUT_DIR/const_get.nm"
grep -q ' void_call$' "$OUT_DIR/statement_workflow.nm"
grep -q ' contract_block_return$' "$OUT_DIR/statement_workflow.nm"
grep -q ' pure_comptime_block$' "$OUT_DIR/comptime.nm"
grep -q ' pure_comptime_nested_block$' "$OUT_DIR/comptime.nm"
grep -q ' direct_array_call_index$' "$OUT_DIR/aggregate_rvalues.nm"
grep -q ' first_from_array_field_call$' "$OUT_DIR/aggregate_rvalues.nm"
grep -q ' bool_and$' "$OUT_DIR/bool_conditions.nm"
grep -q ' require_complex$' "$OUT_DIR/bool_conditions.nm"
grep -q ' first_from_global_array$' "$OUT_DIR/for_loops_full.nm"
grep -q ' second_from_global_nested_row$' "$OUT_DIR/for_loops_full.nm"
grep -q ' first_from_call_array_field$' "$OUT_DIR/for_loops_full.nm"
grep -q ' first_from_call_slice_field$' "$OUT_DIR/for_loops_full.nm"
grep -q ' first_from_array_call_seed$' "$OUT_DIR/for_loops_full.nm"
grep -q ' slice_return$' "$OUT_DIR/slice_ranges.nm"
grep -q ' direct_call_slice_index_return$' "$OUT_DIR/arrays_slices.nm"
grep -q ' local_slice_index_target_both$' "$OUT_DIR/arrays_slices.nm"
grep -q ' same_mut_slice$' "$OUT_DIR/pointer_views.nm"
grep -q ' assign_through_mut_slice$' "$OUT_DIR/pointer_views.nm"
grep -q ' pass_literal_arg$' "$OUT_DIR/string_literals.nm"
grep -q ' return_literal$' "$OUT_DIR/string_literals.nm"
grep -q ' with_escapes$' "$OUT_DIR/string_literals.nm"
grep -q ' fadd$' "$OUT_DIR/floats.nm"
grep -q ' read_bias$' "$OUT_DIR/floats.nm"
grep -q ' trap_as_value$' "$OUT_DIR/trap_never.nm"
grep -q ' never_returns_by_trap$' "$OUT_DIR/trap_never.nm"
grep -q ' read_u32$' "$OUT_DIR/unsafe_machine_ops.nm"
grep -q ' offset_return$' "$OUT_DIR/unsafe_machine_ops.nm"
grep -q ' asm_in_unsafe$' "$OUT_DIR/asm.nm"
grep -q ' find_first_set$' "$OUT_DIR/precise_asm.nm"
grep -q ' combine$' "$OUT_DIR/precise_asm.nm"
grep -q ' double_it$' "$OUT_DIR/precise_asm.nm"
grep -q ' raw_store_in_unsafe$' "$OUT_DIR/unsafe_context.nm"
grep -q ' asm_in_unsafe$' "$OUT_DIR/unsafe_context.nm"
grep -q ' nested_unsafe_raw_store$' "$OUT_DIR/unsafe_context.nm"
grep -q ' mmio_map_in_unsafe$' "$OUT_DIR/unsafe_context.nm"
grep -q ' putc$' "$OUT_DIR/mmio.nm"
grep -q ' status_tx_empty$' "$OUT_DIR/mmio.nm"
grep -q ' read_status$' "$OUT_DIR/mmio_offset.nm"
grep -q ' ring$' "$OUT_DIR/mmio_offset.nm"
grep -q ' ordered_device_sequence$' "$OUT_DIR/mmio_ordering.nm"
grep -q ' program_noncoherent_dma$' "$OUT_DIR/dma_irq_markers.nm"
grep -q ' critical_read$' "$OUT_DIR/dma_irq_markers.nm"
grep -q ' mmio_irq$' "$OUT_DIR/irq_context.nm"
grep -q ' atomic_mmio_irq$' "$OUT_DIR/irq_context.nm"
grep -q ' frame_base$' "$OUT_DIR/addr.nm"
grep -q ' round_up_to_page$' "$OUT_DIR/addr.nm"
grep -q ' pass_paddr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_user_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_const_user_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_phys_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' load_f32$' "$OUT_DIR/float_buffers.nm"
grep -q ' store_f64$' "$OUT_DIR/float_buffers.nm"
grep -q ' kernel_f64$' "$OUT_DIR/float_buffers.nm"
grep -q ' add_mul_sum$' "$OUT_DIR/vector_lanes.nm"
grep -q ' f32x4_load$' "$OUT_DIR/vector_lanes.nm"
grep -q ' f32x4_to_bits$' "$OUT_DIR/vector_lanes.nm"
grep -q ' alias_checked_arithmetic$' "$OUT_DIR/enums_aliases.nm"
grep -q ' classify_irq$' "$OUT_DIR/enums_aliases.nm"
grep -q ' open_enum_raw$' "$OUT_DIR/enums_aliases.nm"
grep -q ' flags_ready$' "$OUT_DIR/declarations.nm"
grep -q ' keep_mode$' "$OUT_DIR/declarations.nm"
grep -q ' copied_value$' "$OUT_DIR/assignment_values.nm"
grep -q ' global_assignment$' "$OUT_DIR/assignment_values.nm"
grep -q ' local_shadows_global_assignment$' "$OUT_DIR/assignment_values.nm"
grep -q ' accept_array_alias$' "$OUT_DIR/type_aliases.nm"
grep -q ' accept_packed_alias$' "$OUT_DIR/type_aliases.nm"
grep -q ' switch_expr_body_order$' "$OUT_DIR/enum_switch.nm"
grep -q ' read_state_raw$' "$OUT_DIR/enum_switch.nm"
grep -q ' unwrap_param$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' unwrap_or$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' nullable_switch$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' make_pair$' "$OUT_DIR/aggregate_abi.nm"
grep -q ' take_pair$' "$OUT_DIR/aggregate_abi.nm"
grep -q ' load_acquire$' "$OUT_DIR/atomics.nm"
grep -q ' fetch_add_acq_rel$' "$OUT_DIR/atomics.nm"
grep -q ' isr_tick$' "$OUT_DIR/atomics.nm"
grep -q ' apply$' "$OUT_DIR/fn_pointers.nm"
grep -q ' dispatch$' "$OUT_DIR/fn_pointers.nm"
grep -q ' global_op_call$' "$OUT_DIR/fn_pointers.nm"
grep -q ' local_fn_pointer_call$' "$OUT_DIR/fn_pointers.nm"
grep -q ' copied_box$' "$OUT_DIR/fn_pointer_full.nm"
grep -q ' copied_global_box_call$' "$OUT_DIR/fn_pointer_full.nm"
grep -q ' replace_global_box$' "$OUT_DIR/fn_pointer_full.nm"
grep -q ' replace_global_box_op$' "$OUT_DIR/fn_pointer_full.nm"
grep -q ' assign_array_literal$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' assign_struct_literal$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' aggregate_call_after_assignment$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' make_pair_box$' "$OUT_DIR/struct_literals.nm"
grep -q ' inferred_call_field_pair$' "$OUT_DIR/struct_literals.nm"
grep -q ' return_call_array$' "$OUT_DIR/array_values.nm"
grep -q ' read_copied_array$' "$OUT_DIR/array_values.nm"
grep -q ' use_u32$' "$OUT_DIR/generic_structs.nm"
grep -q ' make_pair__u32$' "$OUT_DIR/generic_structs.nm"
grep -q ' unwrap_pair_result$' "$OUT_DIR/generic_structs.nm"
grep -q ' fill_size__4$' "$OUT_DIR/monomorphize.nm"
grep -q ' fill_size__8$' "$OUT_DIR/monomorphize.nm"
grep -q ' use_reflected_box_layout$' "$OUT_DIR/monomorphize.nm"
grep -q ' explicit_grouped_uninit_scalar$' "$OUT_DIR/initialization.nm"
grep -q ' explicit_uninit_array_whole_assign_then_read$' "$OUT_DIR/initialization.nm"
grep -q ' maybe_uninit_write_assume_init$' "$OUT_DIR/initialization.nm"
grep -q ' grouped_maybe_uninit_write_assume_init$' "$OUT_DIR/initialization.nm"
grep -q ' make_ok$' "$OUT_DIR/result.nm"
grep -q ' unwrap_ok$' "$OUT_DIR/result.nm"
grep -q ' result_switch_value$' "$OUT_DIR/result.nm"
grep -q ' result_payloadless_switch$' "$OUT_DIR/result.nm"
grep -q ' ok_marker$' "$OUT_DIR/void_result.nm"
grep -q ' err_marker$' "$OUT_DIR/void_result.nm"
grep -q ' switch_result_ok_binding_type$' "$OUT_DIR/if_let_narrowing.nm"
grep -q ' try_in_constructor$' "$OUT_DIR/try_in_expressions.nm"
grep -q ' two_tries_in_arith$' "$OUT_DIR/try_in_expressions.nm"
grep -q ' assign_result_try$' "$OUT_DIR/try_propagation.nm"
grep -q ' result_try_call_expr_rhs_after_call$' "$OUT_DIR/try_propagation.nm"
grep -q ' cleanup_before_return$' "$OUT_DIR/defer.nm"
grep -q ' cleanup_before_break$' "$OUT_DIR/defer_cleanup.nm"
grep -q ' cleanup_before_continue$' "$OUT_DIR/defer_cleanup.nm"
grep -q ' narrow_trap$' "$OUT_DIR/conversions.nm"
grep -q ' narrow_sat$' "$OUT_DIR/conversions.nm"
grep -q ' raw$' "$OUT_DIR/conversions.nm"
grep -q ' wrap_add$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' sat_add$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' inferred_sat_mul$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' seq_before$' "$OUT_DIR/serial_counter.nm"
grep -q ' seq_after$' "$OUT_DIR/serial_counter.nm"
grep -q ' seq_distance$' "$OUT_DIR/serial_counter.nm"
grep -q ' tick_delta$' "$OUT_DIR/serial_counter.nm"
grep -q ' seq_compare$' "$OUT_DIR/library_results.nm"
grep -q ' tick_bounded$' "$OUT_DIR/library_results.nm"
grep -q ' narrow_try$' "$OUT_DIR/library_results.nm"
grep -q ' widen_try$' "$OUT_DIR/library_results.nm"
grep -q ' sum_u32$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' sum_i32$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' sum_u8$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' sum_u64$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' sum_left_f64$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' sum_fast_f32$' "$OUT_DIR/reduce_sum_checked.nm"
grep -q ' wrap_add$' "$OUT_DIR/wrapping_builtin.nm"
grep -q ' allow_wrapping_add$' "$OUT_DIR/no_lang_trap.nm"
grep -q ' allow_saturating_add$' "$OUT_DIR/no_lang_trap.nm"
grep -q ' unchecked_add_inside_contract$' "$OUT_DIR/unsafe_contract.nm"
grep -q ' unchecked_add_return_order$' "$OUT_DIR/unsafe_contract.nm"
grep -q ' unchecked_add_arg_order$' "$OUT_DIR/unsafe_contract.nm"
grep -q ' noalias_contract_region$' "$OUT_DIR/unsafe_contract_scope.nm"
grep -q ' checked_after_contract$' "$OUT_DIR/unsafe_contract_scope.nm"
grep -q ' make_number$' "$OUT_DIR/tagged_union.nm"
grep -q ' token_value$' "$OUT_DIR/tagged_union.nm"
grep -q ' token_call_seed_value$' "$OUT_DIR/tagged_union.nm"
grep -q ' default_slice_len$' "$OUT_DIR/global_initializers.nm"
grep -q ' default_result_value$' "$OUT_DIR/global_initializers.nm"
grep -q ' default_token_value$' "$OUT_DIR/global_initializers.nm"
grep -q ' accept_spec_repr_of_tagged_union$' "$OUT_DIR/reflection.nm"
grep -q ' accept_field_type_type_arg$' "$OUT_DIR/reflection.nm"
grep -q ' reflect_identity__u32$' "$OUT_DIR/reflection.nm"
grep -q ' install$' "$OUT_DIR/global_closure.nm"
grep -q ' invoke$' "$OUT_DIR/global_closure.nm"
grep -q ' invoke_field_direct_at$' "$OUT_DIR/global_closure.nm"
