#!/usr/bin/env sh
set -eu

MCC="${1:?usage: llvm-test.sh path/to/mcc}"
OUT_DIR="${2:-zig-out/llvm-test}"

mkdir -p "$OUT_DIR"
"$MCC" emit-llvm tests/c_emit/smoke.mc > "$OUT_DIR/smoke.ll"
llvm-as "$OUT_DIR/smoke.ll" -o "$OUT_DIR/smoke.bc"
"$MCC" emit-llvm tests/llvm/bool_switch.mc > "$OUT_DIR/bool_switch.ll"
llvm-as "$OUT_DIR/bool_switch.ll" -o "$OUT_DIR/bool_switch.bc"
"$MCC" emit-llvm tests/llvm/loops.mc > "$OUT_DIR/loops.ll"
llvm-as "$OUT_DIR/loops.ll" -o "$OUT_DIR/loops.bc"
"$MCC" emit-llvm tests/llvm/div_rem.mc > "$OUT_DIR/div_rem.ll"
llvm-as "$OUT_DIR/div_rem.ll" -o "$OUT_DIR/div_rem.bc"
"$MCC" emit-llvm tests/llvm/joins.mc > "$OUT_DIR/joins.ll"
llvm-as "$OUT_DIR/joins.ll" -o "$OUT_DIR/joins.bc"
"$MCC" emit-llvm tests/llvm/pointers.mc > "$OUT_DIR/pointers.ll"
llvm-as "$OUT_DIR/pointers.ll" -o "$OUT_DIR/pointers.bc"

grep -q '@llvm.uadd.with.overflow.i32' "$OUT_DIR/smoke.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/smoke.ll"
! grep -q ' nsw ' "$OUT_DIR/smoke.ll"
! grep -q ' nuw ' "$OUT_DIR/smoke.ll"
grep -q 'br i1 %flag' "$OUT_DIR/bool_switch.ll"
grep -q 'icmp ugt i32 %x, 10' "$OUT_DIR/bool_switch.ll"
grep -q 'alloca i32' "$OUT_DIR/loops.ll"
grep -q 'store i32' "$OUT_DIR/loops.ll"
grep -q 'load i32' "$OUT_DIR/loops.ll"
grep -q 'br label %while_cond' "$OUT_DIR/loops.ll"
grep -q '@llvm.usub.with.overflow.i32' "$OUT_DIR/loops.ll"
grep -q 'call void @mc_trap_DivideByZero()' "$OUT_DIR/div_rem.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/div_rem.ll"
grep -q 'sdiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'srem i32' "$OUT_DIR/div_rem.ll"
grep -q 'udiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'urem i32' "$OUT_DIR/div_rem.ll"
grep -q 'switch_end' "$OUT_DIR/joins.ll"
grep -q 'br label %switch_end' "$OUT_DIR/joins.ll"
grep -q 'store i32' "$OUT_DIR/joins.ll"
grep -q 'define i32 @load_ptr(ptr %p)' "$OUT_DIR/pointers.ll"
grep -q 'load i32, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store i32 %value, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store ptr %x.addr, ptr %p.addr' "$OUT_DIR/pointers.ll"
