#!/usr/bin/env sh
set -eu

MCC="${1:?usage: llvm-obj-test.sh path/to/mcc}"
OUT_DIR="${2:-zig-out/llvm-obj-test}"

command -v llc >/dev/null 2>&1 || { echo "SKIP: llvm-obj-test (llc not found)"; exit 0; }
command -v nm >/dev/null 2>&1 || { echo "SKIP: llvm-obj-test (nm not found)"; exit 0; }

mkdir -p "$OUT_DIR"

MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/smoke.mc -o "$OUT_DIR/smoke.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/scalar_expressions.mc -o "$OUT_DIR/scalar_expressions.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/array_literals.mc -o "$OUT_DIR/array_literals.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/arithmetic_checked.mc -o "$OUT_DIR/arithmetic_checked.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/fixed_width_arithmetic.mc -o "$OUT_DIR/fixed_width_arithmetic.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/checked_in_comparison.mc -o "$OUT_DIR/checked_in_comparison.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/bitcast_aliasing.mc -o "$OUT_DIR/bitcast_aliasing.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/const_get.mc -o "$OUT_DIR/const_get.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/statement_workflow.mc -o "$OUT_DIR/statement_workflow.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/comptime.mc -o "$OUT_DIR/comptime.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/aggregate_rvalues.mc -o "$OUT_DIR/aggregate_rvalues.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/bool_conditions.mc -o "$OUT_DIR/bool_conditions.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/char_literals.mc -o "$OUT_DIR/char_literals.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/string_literals.mc -o "$OUT_DIR/string_literals.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/char_arithmetic.mc -o "$OUT_DIR/char_arithmetic.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/floats.mc -o "$OUT_DIR/floats.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/trap_never.mc -o "$OUT_DIR/trap_never.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/unsafe_machine_ops.mc -o "$OUT_DIR/unsafe_machine_ops.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/addr.mc -o "$OUT_DIR/addr.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/address_classes.mc -o "$OUT_DIR/address_classes.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/float_buffers.mc -o "$OUT_DIR/float_buffers.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/vector_lanes.mc -o "$OUT_DIR/vector_lanes.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/enums_aliases.mc -o "$OUT_DIR/enums_aliases.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/declarations.mc -o "$OUT_DIR/declarations.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/type_aliases.mc -o "$OUT_DIR/type_aliases.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/enum_switch.mc -o "$OUT_DIR/enum_switch.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/nullable_pointers.mc -o "$OUT_DIR/nullable_pointers.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/aggregate_abi.mc -o "$OUT_DIR/aggregate_abi.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/aggregate_ordering.mc -o "$OUT_DIR/aggregate_ordering.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/atomics.mc -o "$OUT_DIR/atomics.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/fn_pointers.mc -o "$OUT_DIR/fn_pointers.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/llvm/aggregate_assignments.mc -o "$OUT_DIR/aggregate_assignments.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/initialization.mc -o "$OUT_DIR/initialization.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/conversions.mc -o "$OUT_DIR/conversions.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/arithmetic_domains.mc -o "$OUT_DIR/arithmetic_domains.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/wrapping_builtin.mc -o "$OUT_DIR/wrapping_builtin.o"
MCC="$MCC" tools/toolchain/mcc-llvm-cc.sh tests/c_emit/no_lang_trap.mc -o "$OUT_DIR/no_lang_trap.o"

test -s "$OUT_DIR/smoke.o"
test -s "$OUT_DIR/scalar_expressions.o"
test -s "$OUT_DIR/array_literals.o"
test -s "$OUT_DIR/arithmetic_checked.o"
test -s "$OUT_DIR/fixed_width_arithmetic.o"
test -s "$OUT_DIR/checked_in_comparison.o"
test -s "$OUT_DIR/bitcast_aliasing.o"
test -s "$OUT_DIR/const_get.o"
test -s "$OUT_DIR/statement_workflow.o"
test -s "$OUT_DIR/comptime.o"
test -s "$OUT_DIR/aggregate_rvalues.o"
test -s "$OUT_DIR/bool_conditions.o"
test -s "$OUT_DIR/char_literals.o"
test -s "$OUT_DIR/string_literals.o"
test -s "$OUT_DIR/char_arithmetic.o"
test -s "$OUT_DIR/floats.o"
test -s "$OUT_DIR/trap_never.o"
test -s "$OUT_DIR/unsafe_machine_ops.o"
test -s "$OUT_DIR/addr.o"
test -s "$OUT_DIR/address_classes.o"
test -s "$OUT_DIR/float_buffers.o"
test -s "$OUT_DIR/vector_lanes.o"
test -s "$OUT_DIR/enums_aliases.o"
test -s "$OUT_DIR/declarations.o"
test -s "$OUT_DIR/type_aliases.o"
test -s "$OUT_DIR/enum_switch.o"
test -s "$OUT_DIR/nullable_pointers.o"
test -s "$OUT_DIR/aggregate_abi.o"
test -s "$OUT_DIR/aggregate_ordering.o"
test -s "$OUT_DIR/atomics.o"
test -s "$OUT_DIR/fn_pointers.o"
test -s "$OUT_DIR/aggregate_assignments.o"
test -s "$OUT_DIR/initialization.o"
test -s "$OUT_DIR/conversions.o"
test -s "$OUT_DIR/arithmetic_domains.o"
test -s "$OUT_DIR/wrapping_builtin.o"
test -s "$OUT_DIR/no_lang_trap.o"

nm "$OUT_DIR/smoke.o" > "$OUT_DIR/smoke.nm"
nm "$OUT_DIR/scalar_expressions.o" > "$OUT_DIR/scalar_expressions.nm"
nm "$OUT_DIR/array_literals.o" > "$OUT_DIR/array_literals.nm"
nm "$OUT_DIR/bitcast_aliasing.o" > "$OUT_DIR/bitcast_aliasing.nm"
nm "$OUT_DIR/const_get.o" > "$OUT_DIR/const_get.nm"
nm "$OUT_DIR/statement_workflow.o" > "$OUT_DIR/statement_workflow.nm"
nm "$OUT_DIR/comptime.o" > "$OUT_DIR/comptime.nm"
nm "$OUT_DIR/aggregate_rvalues.o" > "$OUT_DIR/aggregate_rvalues.nm"
nm "$OUT_DIR/bool_conditions.o" > "$OUT_DIR/bool_conditions.nm"
nm "$OUT_DIR/string_literals.o" > "$OUT_DIR/string_literals.nm"
nm "$OUT_DIR/floats.o" > "$OUT_DIR/floats.nm"
nm "$OUT_DIR/trap_never.o" > "$OUT_DIR/trap_never.nm"
nm "$OUT_DIR/unsafe_machine_ops.o" > "$OUT_DIR/unsafe_machine_ops.nm"
nm "$OUT_DIR/addr.o" > "$OUT_DIR/addr.nm"
nm "$OUT_DIR/address_classes.o" > "$OUT_DIR/address_classes.nm"
nm "$OUT_DIR/float_buffers.o" > "$OUT_DIR/float_buffers.nm"
nm "$OUT_DIR/vector_lanes.o" > "$OUT_DIR/vector_lanes.nm"
nm "$OUT_DIR/enums_aliases.o" > "$OUT_DIR/enums_aliases.nm"
nm "$OUT_DIR/declarations.o" > "$OUT_DIR/declarations.nm"
nm "$OUT_DIR/type_aliases.o" > "$OUT_DIR/type_aliases.nm"
nm "$OUT_DIR/enum_switch.o" > "$OUT_DIR/enum_switch.nm"
nm "$OUT_DIR/nullable_pointers.o" > "$OUT_DIR/nullable_pointers.nm"
nm "$OUT_DIR/aggregate_abi.o" > "$OUT_DIR/aggregate_abi.nm"
nm "$OUT_DIR/atomics.o" > "$OUT_DIR/atomics.nm"
nm "$OUT_DIR/fn_pointers.o" > "$OUT_DIR/fn_pointers.nm"
nm "$OUT_DIR/aggregate_assignments.o" > "$OUT_DIR/aggregate_assignments.nm"
nm "$OUT_DIR/initialization.o" > "$OUT_DIR/initialization.nm"
nm "$OUT_DIR/conversions.o" > "$OUT_DIR/conversions.nm"
nm "$OUT_DIR/arithmetic_domains.o" > "$OUT_DIR/arithmetic_domains.nm"
nm "$OUT_DIR/wrapping_builtin.o" > "$OUT_DIR/wrapping_builtin.nm"
nm "$OUT_DIR/no_lang_trap.o" > "$OUT_DIR/no_lang_trap.nm"

grep -q ' add_one$' "$OUT_DIR/smoke.nm"
grep -q ' checked_left_shift$' "$OUT_DIR/scalar_expressions.nm"
grep -q ' flag_set$' "$OUT_DIR/scalar_expressions.nm"
grep -q ' reflected_const_length$' "$OUT_DIR/array_literals.nm"
grep -q ' reflected_field_offset_const_length$' "$OUT_DIR/array_literals.nm"
grep -q ' global_nested_array_row$' "$OUT_DIR/array_literals.nm"
grep -q ' bitcast_float_to_bits$' "$OUT_DIR/bitcast_aliasing.nm"
grep -q ' bitcast_bits_to_float$' "$OUT_DIR/bitcast_aliasing.nm"
grep -q ' pick_const$' "$OUT_DIR/const_get.nm"
grep -q ' pick_checked$' "$OUT_DIR/const_get.nm"
grep -q ' void_call$' "$OUT_DIR/statement_workflow.nm"
grep -q ' contract_block_return$' "$OUT_DIR/statement_workflow.nm"
grep -q ' pure_comptime_block$' "$OUT_DIR/comptime.nm"
grep -q ' pure_comptime_nested_block$' "$OUT_DIR/comptime.nm"
grep -q ' direct_array_call_index$' "$OUT_DIR/aggregate_rvalues.nm"
grep -q ' first_from_array_field_call$' "$OUT_DIR/aggregate_rvalues.nm"
grep -q ' bool_and$' "$OUT_DIR/bool_conditions.nm"
grep -q ' require_complex$' "$OUT_DIR/bool_conditions.nm"
grep -q ' pass_literal_arg$' "$OUT_DIR/string_literals.nm"
grep -q ' return_literal$' "$OUT_DIR/string_literals.nm"
grep -q ' with_escapes$' "$OUT_DIR/string_literals.nm"
grep -q ' fadd$' "$OUT_DIR/floats.nm"
grep -q ' read_bias$' "$OUT_DIR/floats.nm"
grep -q ' trap_as_value$' "$OUT_DIR/trap_never.nm"
grep -q ' never_returns_by_trap$' "$OUT_DIR/trap_never.nm"
grep -q ' read_u32$' "$OUT_DIR/unsafe_machine_ops.nm"
grep -q ' offset_return$' "$OUT_DIR/unsafe_machine_ops.nm"
grep -q ' frame_base$' "$OUT_DIR/addr.nm"
grep -q ' round_up_to_page$' "$OUT_DIR/addr.nm"
grep -q ' pass_paddr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_user_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_const_user_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' keep_phys_ptr$' "$OUT_DIR/address_classes.nm"
grep -q ' load_f32$' "$OUT_DIR/float_buffers.nm"
grep -q ' store_f64$' "$OUT_DIR/float_buffers.nm"
grep -q ' kernel_f64$' "$OUT_DIR/float_buffers.nm"
grep -q ' add_mul_sum$' "$OUT_DIR/vector_lanes.nm"
grep -q ' f32x4_load$' "$OUT_DIR/vector_lanes.nm"
grep -q ' f32x4_to_bits$' "$OUT_DIR/vector_lanes.nm"
grep -q ' alias_checked_arithmetic$' "$OUT_DIR/enums_aliases.nm"
grep -q ' classify_irq$' "$OUT_DIR/enums_aliases.nm"
grep -q ' open_enum_raw$' "$OUT_DIR/enums_aliases.nm"
grep -q ' flags_ready$' "$OUT_DIR/declarations.nm"
grep -q ' keep_mode$' "$OUT_DIR/declarations.nm"
grep -q ' accept_array_alias$' "$OUT_DIR/type_aliases.nm"
grep -q ' accept_packed_alias$' "$OUT_DIR/type_aliases.nm"
grep -q ' switch_expr_body_order$' "$OUT_DIR/enum_switch.nm"
grep -q ' read_state_raw$' "$OUT_DIR/enum_switch.nm"
grep -q ' unwrap_param$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' unwrap_or$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' nullable_switch$' "$OUT_DIR/nullable_pointers.nm"
grep -q ' make_pair$' "$OUT_DIR/aggregate_abi.nm"
grep -q ' take_pair$' "$OUT_DIR/aggregate_abi.nm"
grep -q ' load_acquire$' "$OUT_DIR/atomics.nm"
grep -q ' fetch_add_acq_rel$' "$OUT_DIR/atomics.nm"
grep -q ' isr_tick$' "$OUT_DIR/atomics.nm"
grep -q ' apply$' "$OUT_DIR/fn_pointers.nm"
grep -q ' dispatch$' "$OUT_DIR/fn_pointers.nm"
grep -q ' global_op_call$' "$OUT_DIR/fn_pointers.nm"
grep -q ' local_fn_pointer_call$' "$OUT_DIR/fn_pointers.nm"
grep -q ' assign_array_literal$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' assign_struct_literal$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' aggregate_call_after_assignment$' "$OUT_DIR/aggregate_assignments.nm"
grep -q ' explicit_grouped_uninit_scalar$' "$OUT_DIR/initialization.nm"
grep -q ' read_materialized_uninit_byte$' "$OUT_DIR/initialization.nm"
grep -q ' maybe_uninit_write_assume_init$' "$OUT_DIR/initialization.nm"
grep -q ' narrow_trap$' "$OUT_DIR/conversions.nm"
grep -q ' narrow_sat$' "$OUT_DIR/conversions.nm"
grep -q ' raw$' "$OUT_DIR/conversions.nm"
grep -q ' wrap_add$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' sat_add$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' inferred_sat_mul$' "$OUT_DIR/arithmetic_domains.nm"
grep -q ' wrap_add$' "$OUT_DIR/wrapping_builtin.nm"
grep -q ' allow_wrapping_add$' "$OUT_DIR/no_lang_trap.nm"
grep -q ' allow_saturating_add$' "$OUT_DIR/no_lang_trap.nm"
