#!/usr/bin/env sh
set -eu

MCC="${1:?usage: llvm-test.sh path/to/mcc}"
OUT_DIR="${2:-zig-out/llvm-test}"

mkdir -p "$OUT_DIR"
"$MCC" emit-llvm tests/c_emit/smoke.mc > "$OUT_DIR/smoke.ll"
llvm-as "$OUT_DIR/smoke.ll" -o "$OUT_DIR/smoke.bc"
"$MCC" emit-llvm tests/llvm/bool_switch.mc > "$OUT_DIR/bool_switch.ll"
llvm-as "$OUT_DIR/bool_switch.ll" -o "$OUT_DIR/bool_switch.bc"
"$MCC" emit-llvm tests/llvm/loops.mc > "$OUT_DIR/loops.ll"
llvm-as "$OUT_DIR/loops.ll" -o "$OUT_DIR/loops.bc"
"$MCC" emit-llvm tests/llvm/div_rem.mc > "$OUT_DIR/div_rem.ll"
llvm-as "$OUT_DIR/div_rem.ll" -o "$OUT_DIR/div_rem.bc"
"$MCC" emit-llvm tests/llvm/joins.mc > "$OUT_DIR/joins.ll"
llvm-as "$OUT_DIR/joins.ll" -o "$OUT_DIR/joins.bc"
"$MCC" emit-llvm tests/llvm/pointers.mc > "$OUT_DIR/pointers.ll"
llvm-as "$OUT_DIR/pointers.ll" -o "$OUT_DIR/pointers.bc"
"$MCC" emit-llvm tests/llvm/globals.mc > "$OUT_DIR/globals.ll"
llvm-as "$OUT_DIR/globals.ll" -o "$OUT_DIR/globals.bc"
"$MCC" emit-llvm tests/llvm/arrays.mc > "$OUT_DIR/arrays.ll"
llvm-as "$OUT_DIR/arrays.ll" -o "$OUT_DIR/arrays.bc"
"$MCC" emit-llvm tests/c_emit/array_literals.mc > "$OUT_DIR/array_literals.ll"
llvm-as "$OUT_DIR/array_literals.ll" -o "$OUT_DIR/array_literals.bc"
"$MCC" emit-llvm tests/llvm/structs.mc > "$OUT_DIR/structs.ll"
llvm-as "$OUT_DIR/structs.ll" -o "$OUT_DIR/structs.bc"
"$MCC" emit-llvm tests/llvm/aggregate_globals.mc > "$OUT_DIR/aggregate_globals.ll"
llvm-as "$OUT_DIR/aggregate_globals.ll" -o "$OUT_DIR/aggregate_globals.bc"
"$MCC" emit-llvm tests/llvm/aggregate_abi.mc > "$OUT_DIR/aggregate_abi.ll"
llvm-as "$OUT_DIR/aggregate_abi.ll" -o "$OUT_DIR/aggregate_abi.bc"
"$MCC" emit-llvm tests/llvm/nested_aggregates.mc > "$OUT_DIR/nested_aggregates.ll"
llvm-as "$OUT_DIR/nested_aggregates.ll" -o "$OUT_DIR/nested_aggregates.bc"
"$MCC" emit-llvm tests/c_emit/aggregate_ordering.mc > "$OUT_DIR/aggregate_ordering.ll"
llvm-as "$OUT_DIR/aggregate_ordering.ll" -o "$OUT_DIR/aggregate_ordering.bc"
"$MCC" emit-llvm tests/llvm/slices.mc > "$OUT_DIR/slices.ll"
llvm-as "$OUT_DIR/slices.ll" -o "$OUT_DIR/slices.bc"
"$MCC" emit-llvm tests/c_emit/slice_ranges.mc > "$OUT_DIR/slice_ranges.ll"
llvm-as "$OUT_DIR/slice_ranges.ll" -o "$OUT_DIR/slice_ranges.bc"
"$MCC" emit-llvm tests/c_emit/arrays_slices.mc > "$OUT_DIR/arrays_slices.ll"
llvm-as "$OUT_DIR/arrays_slices.ll" -o "$OUT_DIR/arrays_slices.bc"
"$MCC" emit-llvm tests/c_emit/pointer_views.mc > "$OUT_DIR/pointer_views.ll"
llvm-as "$OUT_DIR/pointer_views.ll" -o "$OUT_DIR/pointer_views.bc"
"$MCC" emit-llvm tests/llvm/scalar_switch.mc > "$OUT_DIR/scalar_switch.ll"
llvm-as "$OUT_DIR/scalar_switch.ll" -o "$OUT_DIR/scalar_switch.bc"
"$MCC" emit-llvm tests/llvm/for_loops.mc > "$OUT_DIR/for_loops.ll"
llvm-as "$OUT_DIR/for_loops.ll" -o "$OUT_DIR/for_loops.bc"
"$MCC" emit-llvm tests/c_emit/for_loops.mc > "$OUT_DIR/for_loops_full.ll"
llvm-as "$OUT_DIR/for_loops_full.ll" -o "$OUT_DIR/for_loops_full.bc"
"$MCC" emit-llvm tests/llvm/scalar_expressions.mc > "$OUT_DIR/scalar_expressions.ll"
llvm-as "$OUT_DIR/scalar_expressions.ll" -o "$OUT_DIR/scalar_expressions.bc"
"$MCC" emit-llvm tests/c_emit/arithmetic_checked.mc > "$OUT_DIR/arithmetic_checked.ll"
llvm-as "$OUT_DIR/arithmetic_checked.ll" -o "$OUT_DIR/arithmetic_checked.bc"
"$MCC" emit-llvm tests/c_emit/fixed_width_arithmetic.mc > "$OUT_DIR/fixed_width_arithmetic.ll"
llvm-as "$OUT_DIR/fixed_width_arithmetic.ll" -o "$OUT_DIR/fixed_width_arithmetic.bc"
"$MCC" emit-llvm tests/c_emit/checked_in_comparison.mc > "$OUT_DIR/checked_in_comparison.ll"
llvm-as "$OUT_DIR/checked_in_comparison.ll" -o "$OUT_DIR/checked_in_comparison.bc"
"$MCC" emit-llvm tests/c_emit/bitcast_aliasing.mc > "$OUT_DIR/bitcast_aliasing.ll"
llvm-as "$OUT_DIR/bitcast_aliasing.ll" -o "$OUT_DIR/bitcast_aliasing.bc"
"$MCC" emit-llvm tests/c_emit/byte_views.mc > "$OUT_DIR/byte_views.ll"
llvm-as "$OUT_DIR/byte_views.ll" -o "$OUT_DIR/byte_views.bc"
"$MCC" emit-llvm tests/c_emit/packed_overlay.mc > "$OUT_DIR/packed_overlay.ll"
llvm-as "$OUT_DIR/packed_overlay.ll" -o "$OUT_DIR/packed_overlay.bc"
"$MCC" emit-llvm tests/c_emit/packed_bits_overlay.mc > "$OUT_DIR/packed_bits_overlay.ll"
llvm-as "$OUT_DIR/packed_bits_overlay.ll" -o "$OUT_DIR/packed_bits_overlay.bc"
"$MCC" emit-llvm tests/c_emit/const_get.mc > "$OUT_DIR/const_get.ll"
llvm-as "$OUT_DIR/const_get.ll" -o "$OUT_DIR/const_get.bc"
"$MCC" emit-llvm tests/c_emit/char_literals.mc > "$OUT_DIR/char_literals.ll"
llvm-as "$OUT_DIR/char_literals.ll" -o "$OUT_DIR/char_literals.bc"
"$MCC" emit-llvm tests/c_emit/string_literals.mc > "$OUT_DIR/string_literals.ll"
llvm-as "$OUT_DIR/string_literals.ll" -o "$OUT_DIR/string_literals.bc"
"$MCC" emit-llvm tests/c_emit/char_arithmetic.mc > "$OUT_DIR/char_arithmetic.ll"
llvm-as "$OUT_DIR/char_arithmetic.ll" -o "$OUT_DIR/char_arithmetic.bc"
"$MCC" emit-llvm tests/llvm/statement_workflow.mc > "$OUT_DIR/statement_workflow.ll"
llvm-as "$OUT_DIR/statement_workflow.ll" -o "$OUT_DIR/statement_workflow.bc"
"$MCC" emit-llvm tests/c_emit/comptime.mc > "$OUT_DIR/comptime.ll"
llvm-as "$OUT_DIR/comptime.ll" -o "$OUT_DIR/comptime.bc"
"$MCC" emit-llvm tests/llvm/aggregate_rvalues.mc > "$OUT_DIR/aggregate_rvalues.ll"
llvm-as "$OUT_DIR/aggregate_rvalues.ll" -o "$OUT_DIR/aggregate_rvalues.bc"
"$MCC" emit-llvm tests/llvm/bool_conditions.mc > "$OUT_DIR/bool_conditions.ll"
llvm-as "$OUT_DIR/bool_conditions.ll" -o "$OUT_DIR/bool_conditions.bc"
"$MCC" emit-llvm tests/llvm/floats.mc > "$OUT_DIR/floats.ll"
llvm-as "$OUT_DIR/floats.ll" -o "$OUT_DIR/floats.bc"
"$MCC" emit-llvm tests/c_emit/float_negation.mc > "$OUT_DIR/float_negation.ll"
llvm-as "$OUT_DIR/float_negation.ll" -o "$OUT_DIR/float_negation.bc"
"$MCC" emit-llvm tests/llvm/trap_never.mc > "$OUT_DIR/trap_never.ll"
llvm-as "$OUT_DIR/trap_never.ll" -o "$OUT_DIR/trap_never.bc"
"$MCC" emit-llvm tests/llvm/unsafe_machine_ops.mc > "$OUT_DIR/unsafe_machine_ops.ll"
llvm-as "$OUT_DIR/unsafe_machine_ops.ll" -o "$OUT_DIR/unsafe_machine_ops.bc"
"$MCC" emit-llvm tests/c_emit/asm.mc > "$OUT_DIR/asm.ll"
llvm-as "$OUT_DIR/asm.ll" -o "$OUT_DIR/asm.bc"
"$MCC" emit-llvm tests/c_emit/precise_asm.mc > "$OUT_DIR/precise_asm.ll"
llvm-as "$OUT_DIR/precise_asm.ll" -o "$OUT_DIR/precise_asm.bc"
"$MCC" emit-llvm tests/c_emit/unsafe_context.mc > "$OUT_DIR/unsafe_context.ll"
llvm-as "$OUT_DIR/unsafe_context.ll" -o "$OUT_DIR/unsafe_context.bc"
"$MCC" emit-llvm tests/c_emit/mmio.mc > "$OUT_DIR/mmio.ll"
llvm-as "$OUT_DIR/mmio.ll" -o "$OUT_DIR/mmio.bc"
"$MCC" emit-llvm tests/c_emit/mmio_offset.mc > "$OUT_DIR/mmio_offset.ll"
llvm-as "$OUT_DIR/mmio_offset.ll" -o "$OUT_DIR/mmio_offset.bc"
"$MCC" emit-llvm tests/c_emit/mmio_ordering.mc > "$OUT_DIR/mmio_ordering.ll"
llvm-as "$OUT_DIR/mmio_ordering.ll" -o "$OUT_DIR/mmio_ordering.bc"
"$MCC" emit-llvm tests/llvm/dma_irq_markers.mc > "$OUT_DIR/dma_irq_markers.ll"
llvm-as "$OUT_DIR/dma_irq_markers.ll" -o "$OUT_DIR/dma_irq_markers.bc"
"$MCC" emit-llvm tests/c_emit/irq_context.mc > "$OUT_DIR/irq_context.ll"
llvm-as "$OUT_DIR/irq_context.ll" -o "$OUT_DIR/irq_context.bc"
"$MCC" emit-llvm tests/c_emit/addr.mc > "$OUT_DIR/addr.ll"
llvm-as "$OUT_DIR/addr.ll" -o "$OUT_DIR/addr.bc"
"$MCC" emit-llvm tests/c_emit/address_classes.mc > "$OUT_DIR/address_classes.ll"
llvm-as "$OUT_DIR/address_classes.ll" -o "$OUT_DIR/address_classes.bc"
"$MCC" emit-llvm tests/c_emit/float_buffers.mc > "$OUT_DIR/float_buffers.ll"
llvm-as "$OUT_DIR/float_buffers.ll" -o "$OUT_DIR/float_buffers.bc"
"$MCC" emit-llvm tests/c_emit/vector_lanes.mc > "$OUT_DIR/vector_lanes.ll"
llvm-as "$OUT_DIR/vector_lanes.ll" -o "$OUT_DIR/vector_lanes.bc"
"$MCC" emit-llvm tests/llvm/enums_aliases.mc > "$OUT_DIR/enums_aliases.ll"
llvm-as "$OUT_DIR/enums_aliases.ll" -o "$OUT_DIR/enums_aliases.bc"
"$MCC" emit-llvm tests/c_emit/declarations.mc > "$OUT_DIR/declarations.ll"
llvm-as "$OUT_DIR/declarations.ll" -o "$OUT_DIR/declarations.bc"
"$MCC" emit-llvm tests/c_emit/assignment_values.mc > "$OUT_DIR/assignment_values.ll"
llvm-as "$OUT_DIR/assignment_values.ll" -o "$OUT_DIR/assignment_values.bc"
"$MCC" emit-llvm tests/c_emit/type_aliases.mc > "$OUT_DIR/type_aliases.ll"
llvm-as "$OUT_DIR/type_aliases.ll" -o "$OUT_DIR/type_aliases.bc"
"$MCC" emit-llvm tests/c_emit/enum_switch.mc > "$OUT_DIR/enum_switch.ll"
llvm-as "$OUT_DIR/enum_switch.ll" -o "$OUT_DIR/enum_switch.bc"
"$MCC" emit-llvm tests/llvm/nullable_pointers.mc > "$OUT_DIR/nullable_pointers.ll"
llvm-as "$OUT_DIR/nullable_pointers.ll" -o "$OUT_DIR/nullable_pointers.bc"
"$MCC" emit-llvm tests/llvm/atomics.mc > "$OUT_DIR/atomics.ll"
llvm-as "$OUT_DIR/atomics.ll" -o "$OUT_DIR/atomics.bc"
"$MCC" emit-llvm tests/llvm/fn_pointers.mc > "$OUT_DIR/fn_pointers.ll"
llvm-as "$OUT_DIR/fn_pointers.ll" -o "$OUT_DIR/fn_pointers.bc"
"$MCC" emit-llvm tests/c_emit/fn_pointer.mc > "$OUT_DIR/fn_pointer_full.ll"
llvm-as "$OUT_DIR/fn_pointer_full.ll" -o "$OUT_DIR/fn_pointer_full.bc"
"$MCC" emit-llvm tests/llvm/aggregate_assignments.mc > "$OUT_DIR/aggregate_assignments.ll"
llvm-as "$OUT_DIR/aggregate_assignments.ll" -o "$OUT_DIR/aggregate_assignments.bc"
"$MCC" emit-llvm tests/c_emit/struct_literals.mc > "$OUT_DIR/struct_literals.ll"
llvm-as "$OUT_DIR/struct_literals.ll" -o "$OUT_DIR/struct_literals.bc"
"$MCC" emit-llvm tests/c_emit/array_values.mc > "$OUT_DIR/array_values.ll"
llvm-as "$OUT_DIR/array_values.ll" -o "$OUT_DIR/array_values.bc"
"$MCC" emit-llvm tests/c_emit/generic_structs.mc > "$OUT_DIR/generic_structs.ll"
llvm-as "$OUT_DIR/generic_structs.ll" -o "$OUT_DIR/generic_structs.bc"
"$MCC" emit-llvm tests/c_emit/monomorphize.mc > "$OUT_DIR/monomorphize.ll"
llvm-as "$OUT_DIR/monomorphize.ll" -o "$OUT_DIR/monomorphize.bc"
"$MCC" emit-llvm tests/c_emit/initialization.mc > "$OUT_DIR/initialization.ll"
llvm-as "$OUT_DIR/initialization.ll" -o "$OUT_DIR/initialization.bc"
"$MCC" emit-llvm tests/c_emit/result.mc > "$OUT_DIR/result.ll"
llvm-as "$OUT_DIR/result.ll" -o "$OUT_DIR/result.bc"
"$MCC" emit-llvm tests/c_emit/void_result.mc > "$OUT_DIR/void_result.ll"
llvm-as "$OUT_DIR/void_result.ll" -o "$OUT_DIR/void_result.bc"
"$MCC" emit-llvm tests/c_emit/if_let_narrowing.mc > "$OUT_DIR/if_let_narrowing.ll"
llvm-as "$OUT_DIR/if_let_narrowing.ll" -o "$OUT_DIR/if_let_narrowing.bc"
"$MCC" emit-llvm tests/c_emit/try_in_expressions.mc > "$OUT_DIR/try_in_expressions.ll"
llvm-as "$OUT_DIR/try_in_expressions.ll" -o "$OUT_DIR/try_in_expressions.bc"
"$MCC" emit-llvm tests/c_emit/try_propagation.mc > "$OUT_DIR/try_propagation.ll"
llvm-as "$OUT_DIR/try_propagation.ll" -o "$OUT_DIR/try_propagation.bc"
"$MCC" emit-llvm tests/c_emit/defer.mc > "$OUT_DIR/defer.ll"
llvm-as "$OUT_DIR/defer.ll" -o "$OUT_DIR/defer.bc"
"$MCC" emit-llvm tests/c_emit/defer_cleanup.mc > "$OUT_DIR/defer_cleanup.ll"
llvm-as "$OUT_DIR/defer_cleanup.ll" -o "$OUT_DIR/defer_cleanup.bc"
"$MCC" emit-llvm tests/c_emit/conversions.mc > "$OUT_DIR/conversions.ll"
llvm-as "$OUT_DIR/conversions.ll" -o "$OUT_DIR/conversions.bc"
"$MCC" emit-llvm tests/c_emit/arithmetic_domains.mc > "$OUT_DIR/arithmetic_domains.ll"
llvm-as "$OUT_DIR/arithmetic_domains.ll" -o "$OUT_DIR/arithmetic_domains.bc"
"$MCC" emit-llvm tests/c_emit/serial_counter.mc > "$OUT_DIR/serial_counter.ll"
llvm-as "$OUT_DIR/serial_counter.ll" -o "$OUT_DIR/serial_counter.bc"
"$MCC" emit-llvm tests/c_emit/library_results.mc > "$OUT_DIR/library_results.ll"
llvm-as "$OUT_DIR/library_results.ll" -o "$OUT_DIR/library_results.bc"
"$MCC" emit-llvm tests/c_emit/reduce_sum_checked.mc > "$OUT_DIR/reduce_sum_checked.ll"
llvm-as "$OUT_DIR/reduce_sum_checked.ll" -o "$OUT_DIR/reduce_sum_checked.bc"
"$MCC" emit-llvm tests/c_emit/wrapping_builtin.mc > "$OUT_DIR/wrapping_builtin.ll"
llvm-as "$OUT_DIR/wrapping_builtin.ll" -o "$OUT_DIR/wrapping_builtin.bc"
"$MCC" emit-llvm tests/c_emit/no_lang_trap.mc > "$OUT_DIR/no_lang_trap.ll"
llvm-as "$OUT_DIR/no_lang_trap.ll" -o "$OUT_DIR/no_lang_trap.bc"
"$MCC" emit-llvm tests/llvm/no_lang_trap_valid.mc > "$OUT_DIR/no_lang_trap_valid.ll"
llvm-as "$OUT_DIR/no_lang_trap_valid.ll" -o "$OUT_DIR/no_lang_trap_valid.bc"
"$MCC" emit-llvm tests/llvm/move_linear_valid.mc > "$OUT_DIR/move_linear_valid.ll"
llvm-as "$OUT_DIR/move_linear_valid.ll" -o "$OUT_DIR/move_linear_valid.bc"
"$MCC" emit-llvm tests/c_emit/unsafe_contract.mc > "$OUT_DIR/unsafe_contract.ll"
llvm-as "$OUT_DIR/unsafe_contract.ll" -o "$OUT_DIR/unsafe_contract.bc"
"$MCC" emit-llvm tests/c_emit/unsafe_contract_scope.mc > "$OUT_DIR/unsafe_contract_scope.ll"
llvm-as "$OUT_DIR/unsafe_contract_scope.ll" -o "$OUT_DIR/unsafe_contract_scope.bc"
"$MCC" emit-llvm tests/c_emit/tagged_union.mc > "$OUT_DIR/tagged_union.ll"
llvm-as "$OUT_DIR/tagged_union.ll" -o "$OUT_DIR/tagged_union.bc"
"$MCC" emit-llvm tests/c_emit/global_initializers.mc > "$OUT_DIR/global_initializers.ll"
llvm-as "$OUT_DIR/global_initializers.ll" -o "$OUT_DIR/global_initializers.bc"
"$MCC" emit-llvm tests/c_emit/reflection.mc > "$OUT_DIR/reflection.ll"
llvm-as "$OUT_DIR/reflection.ll" -o "$OUT_DIR/reflection.bc"
"$MCC" emit-llvm tests/c_emit/global_closure.mc > "$OUT_DIR/global_closure.ll"
llvm-as "$OUT_DIR/global_closure.ll" -o "$OUT_DIR/global_closure.bc"

grep -q '@llvm.uadd.with.overflow.i32' "$OUT_DIR/smoke.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/smoke.ll"
! grep -q ' nsw ' "$OUT_DIR/smoke.ll"
! grep -q ' nuw ' "$OUT_DIR/smoke.ll"
grep -q 'source_filename = "tests/c_emit/smoke.mc"' "$OUT_DIR/smoke.ll"
grep -q '!llvm.dbg.cu = !{!0}' "$OUT_DIR/smoke.ll"
grep -q '!DICompileUnit' "$OUT_DIR/smoke.ll"
grep -q '!DISubprogram(name: "add_one"' "$OUT_DIR/smoke.ll"
grep -q 'ret i32 .* !dbg !' "$OUT_DIR/smoke.ll"
grep -q '!DILocation(line: 2, column: 5, scope: !' "$OUT_DIR/smoke.ll"
grep -q '!DILocation(line: 6, column: 5, scope: !' "$OUT_DIR/smoke.ll"
grep -q 'store i32 %value, ptr %out.addr, !dbg !' "$OUT_DIR/statement_workflow.ll"
grep -q 'store i32 %t1, ptr %out.addr, !dbg !' "$OUT_DIR/statement_workflow.ll"
grep -q '!DILocation(line: 13, column: 9, scope: !' "$OUT_DIR/statement_workflow.ll"
grep -q '!DILocation(line: 36, column: 5, scope: !' "$OUT_DIR/statement_workflow.ll"
grep -q 'switch i1 %flag' "$OUT_DIR/bool_switch.ll"
grep -q '\], !dbg !' "$OUT_DIR/bool_switch.ll"
grep -q 'call void @mc_trap_InvalidRepresentation()' "$OUT_DIR/bool_switch.ll"
grep -q 'icmp ugt i32 %x, 10' "$OUT_DIR/bool_switch.ll"
grep -q 'alloca i32' "$OUT_DIR/loops.ll"
grep -q 'store i32' "$OUT_DIR/loops.ll"
grep -q 'load i32' "$OUT_DIR/loops.ll"
grep -q 'br label %while_cond' "$OUT_DIR/loops.ll"
grep -q 'br label %while_cond.*, !dbg !' "$OUT_DIR/loops.ll"
grep -q 'br i1 .* label %while_body.*, label %while_end.*, !dbg !' "$OUT_DIR/loops.ll"
grep -q '@llvm.usub.with.overflow.i32' "$OUT_DIR/loops.ll"
grep -q 'call void @mc_trap_DivideByZero()' "$OUT_DIR/div_rem.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/div_rem.ll"
grep -q 'sdiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'srem i32' "$OUT_DIR/div_rem.ll"
grep -q 'udiv i32' "$OUT_DIR/div_rem.ll"
grep -q 'urem i32' "$OUT_DIR/div_rem.ll"
grep -q 'switch_end' "$OUT_DIR/joins.ll"
grep -q 'br label %switch_end' "$OUT_DIR/joins.ll"
grep -q 'store i32' "$OUT_DIR/joins.ll"
grep -q 'define i32 @load_ptr(ptr %p)' "$OUT_DIR/pointers.ll"
grep -q 'load i32, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store i32 %value, ptr %p' "$OUT_DIR/pointers.ll"
grep -q 'store ptr %x.addr, ptr %p.addr' "$OUT_DIR/pointers.ll"
grep -q '@shared = global i32 7' "$OUT_DIR/globals.ll"
grep -q '@flag = global i1 0' "$OUT_DIR/globals.ll"
grep -q '@shared_ptr = global ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'load i32, ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'store i32 %value, ptr @shared' "$OUT_DIR/globals.ll"
grep -q 'alloca \[2 x i32\]' "$OUT_DIR/arrays.ll"
grep -q 'getelementptr inbounds \[2 x i32\]' "$OUT_DIR/arrays.ll"
grep -q 'call void @mc_trap_Bounds()' "$OUT_DIR/arrays.ll"
grep -q 'store ptr %t' "$OUT_DIR/arrays.ll"
grep -q '@WORD_SIZE = constant i64 4' "$OUT_DIR/array_literals.ll"
grep -q '@PACKET_TAG_OFFSET = constant i64 2' "$OUT_DIR/array_literals.ll"
grep -q '@default_matrix = global \[2 x \[2 x i32\]\]' "$OUT_DIR/array_literals.ll"
grep -q 'define i8 @reflected_const_length()' "$OUT_DIR/array_literals.ll"
grep -q 'alloca \[4 x i8\]' "$OUT_DIR/array_literals.ll"
grep -q 'define i8 @reflected_field_offset_const_length()' "$OUT_DIR/array_literals.ll"
grep -q 'alloca \[2 x i8\]' "$OUT_DIR/array_literals.ll"
grep -q 'define \[2 x i32\] @global_nested_array_row()' "$OUT_DIR/array_literals.ll"
grep -q 'alloca { i32, i32 }' "$OUT_DIR/structs.ll"
grep -q 'getelementptr inbounds { i32, i32 }' "$OUT_DIR/structs.ll"
grep -q 'store i32 %value, ptr %t' "$OUT_DIR/structs.ll"
grep -q 'store ptr %t' "$OUT_DIR/structs.ll"
grep -q '@values = global \[2 x i32\] \[i32 10, i32 20\]' "$OUT_DIR/aggregate_globals.ll"
grep -q '@pair = global { i32, i32 } { i32 1, i32 2 }' "$OUT_DIR/aggregate_globals.ll"
grep -q 'getelementptr inbounds \[2 x i32\], ptr @values' "$OUT_DIR/aggregate_globals.ll"
grep -q 'getelementptr inbounds { i32, i32 }, ptr @pair' "$OUT_DIR/aggregate_globals.ll"
grep -q 'define { i32, i32 } @make_pair()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'define i32 @take_pair({ i32, i32 } %pair)' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call { i32, i32 } @make_pair()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call i32 @take_pair({ i32, i32 }' "$OUT_DIR/aggregate_abi.ll"
grep -q 'define \[2 x i32\] @make_row()' "$OUT_DIR/aggregate_abi.ll"
grep -q 'call i32 @take_row(\[2 x i32\]' "$OUT_DIR/aggregate_abi.ll"
grep -q '@matrix = global \[2 x \[2 x i32\]\]' "$OUT_DIR/nested_aggregates.ll"
grep -q '@box = global { { i32, i32 } }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds \[2 x \[2 x i32\]\]' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds { { i32, i32 } }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'getelementptr inbounds { i32, i32 }' "$OUT_DIR/nested_aggregates.ll"
grep -q 'define i32 @slice_of_struct({ ptr, i64 } %xs)' "$OUT_DIR/aggregate_ordering.ll"
grep -q 'trunc i64 %t.* to i32' "$OUT_DIR/aggregate_ordering.ll"
grep -q 'define i32 @nested({ { \[3 x { i32 }\], i32 }, { ptr, i64 } } %o)' "$OUT_DIR/aggregate_ordering.ll"
grep -q 'define i32 @slice_of_array({ ptr, i64 } %rows)' "$OUT_DIR/aggregate_ordering.ll"
grep -q 'declare { ptr, i64 } @make_u8_slice()' "$OUT_DIR/slices.ll"
grep -q 'define i8 @read_slice({ ptr, i64 } %xs, i64 %i)' "$OUT_DIR/slices.ll"
grep -q 'define { ptr, i64 } @same_slice({ ptr, i64 } %xs)' "$OUT_DIR/slices.ll"
grep -q 'extractvalue { ptr, i64 }' "$OUT_DIR/slices.ll"
grep -q 'insertvalue { ptr, i64 } undef, ptr' "$OUT_DIR/slices.ll"
grep -q 'define i8 @inferred_slice_call_base_arg()' "$OUT_DIR/slices.ll"
grep -q 'define i8 @inferred_array_call_base()' "$OUT_DIR/slices.ll"
grep -q 'getelementptr inbounds i8, ptr' "$OUT_DIR/slices.ll"
grep -q 'icmp ule i64' "$OUT_DIR/slices.ll"
grep -q 'define i8 @slice_first({ ptr, i64 } %buf, i64 %n)' "$OUT_DIR/slice_ranges.ll"
grep -q 'define { ptr, i64 } @slice_return({ ptr, i64 } %buf, i64 %lo, i64 %hi)' "$OUT_DIR/slice_ranges.ll"
grep -q 'sub i64 %hi, %lo' "$OUT_DIR/slice_ranges.ll"
grep -q 'insertvalue { ptr, i64 }' "$OUT_DIR/slice_ranges.ll"
grep -q 'define i8 @direct_call_slice_index_return()' "$OUT_DIR/arrays_slices.ll"
grep -q 'define void @local_slice_index_target_both({ ptr, i64 } %xs)' "$OUT_DIR/arrays_slices.ll"
grep -q 'define i8 @direct_call_array_index_return()' "$OUT_DIR/arrays_slices.ll"
grep -q 'call { ptr, i64 } @make_slice_from(i8' "$OUT_DIR/arrays_slices.ll"
grep -q 'call \[4 x i8\] @make_array_from(i8' "$OUT_DIR/arrays_slices.ll"
grep -q 'define { ptr, i64 } @same_mut_slice({ ptr, i64 } %xs)' "$OUT_DIR/pointer_views.ll"
grep -q 'define { ptr, i64 } @same_const_slice({ ptr, i64 } %xs)' "$OUT_DIR/pointer_views.ll"
grep -q 'define void @assign_through_mut_slice({ ptr, i64 } %xs, i64 %i, i32 %value)' "$OUT_DIR/pointer_views.ll"
grep -q 'store i32 %value, ptr %t' "$OUT_DIR/pointer_views.ll"
grep -q 'switch i32 %n' "$OUT_DIR/scalar_switch.ll"
grep -q '\], !dbg !' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 1, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 2, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'switch i8 %c' "$OUT_DIR/scalar_switch.ll"
grep -q 'i8 65, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i8 10, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'switch i32 %n, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'i32 -1, label %switch_arm' "$OUT_DIR/scalar_switch.ll"
grep -q 'br label %for_cond' "$OUT_DIR/for_loops.ll"
grep -q 'br label %for_cond.*, !dbg !' "$OUT_DIR/for_loops.ll"
grep -q 'br i1 .* label %for_body.*, label %for_end.*, !dbg !' "$OUT_DIR/for_loops.ll"
grep -q 'br label %for_step.*, !dbg !' "$OUT_DIR/for_loops.ll"
grep -q 'br label %for_end.*, !dbg !' "$OUT_DIR/for_loops.ll"
grep -q 'for_body' "$OUT_DIR/for_loops.ll"
grep -q 'for_step' "$OUT_DIR/for_loops.ll"
grep -q 'for_end' "$OUT_DIR/for_loops.ll"
grep -q 'getelementptr inbounds i32, ptr' "$OUT_DIR/for_loops.ll"
grep -q 'getelementptr inbounds \[4 x i32\]' "$OUT_DIR/for_loops.ll"
grep -q 'call { ptr, i64 } @make_u32_slice()' "$OUT_DIR/for_loops.ll"
grep -q 'br label %while_end' "$OUT_DIR/for_loops.ll"
grep -q 'br label %while_cond' "$OUT_DIR/for_loops.ll"
grep -q '@global_matrix = global \[2 x \[2 x i32\]\]' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @first_from_global_array()' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @second_from_global_nested_row()' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @first_from_array_field({ \[3 x i32\], \[2 x \[2 x i32\]\] } %bag)' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @first_from_call_array_field()' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @first_from_call_slice_field()' "$OUT_DIR/for_loops_full.ll"
grep -q 'define i32 @first_from_array_call_seed()' "$OUT_DIR/for_loops_full.ll"
grep -q 'call \[4 x i32\] @make_u32_array_from' "$OUT_DIR/for_loops_full.ll"
grep -q ' and i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q ' or i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q ' xor i32 ' "$OUT_DIR/scalar_expressions.ll"
grep -q 'shl i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'lshr i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'zext i32' "$OUT_DIR/scalar_expressions.ll"
grep -q 'trunc i64' "$OUT_DIR/scalar_expressions.ll"
grep -q 'call void @mc_trap_InvalidShift()' "$OUT_DIR/scalar_expressions.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/scalar_expressions.ll"
grep -q 'define i32 @signed_neg_min_overflow()' "$OUT_DIR/arithmetic_checked.ll"
grep -q 'icmp eq i32 .* -2147483648' "$OUT_DIR/arithmetic_checked.ll"
grep -q 'trap_neg_overflow' "$OUT_DIR/fixed_width_arithmetic.ll"
grep -q 'sub i64 0, %a' "$OUT_DIR/fixed_width_arithmetic.ll"
grep -q 'define i1 @neg_signed(i32 %a, i32 %b)' "$OUT_DIR/checked_in_comparison.ll"
grep -q 'define i32 @bitcast_return(i32 %x)' "$OUT_DIR/bitcast_aliasing.ll"
grep -q 'call void @consume_u32(i32 %x)' "$OUT_DIR/bitcast_aliasing.ll"
grep -q 'bitcast float %x to i32' "$OUT_DIR/bitcast_aliasing.ll"
grep -q 'bitcast i32 %x to float' "$OUT_DIR/bitcast_aliasing.ll"
grep -q 'define i8 @as_bytes_index()' "$OUT_DIR/byte_views.ll"
grep -q 'insertvalue { ptr, i64 } .* i64 8, 1' "$OUT_DIR/byte_views.ll"
grep -q 'define i1 @bytes_equal_pair()' "$OUT_DIR/byte_views.ll"
grep -q 'bytes_equal_cond' "$OUT_DIR/byte_views.ll"
grep -q 'icmp eq i8' "$OUT_DIR/byte_views.ll"
grep -q 'define i1 @bytes_equal_local_slices()' "$OUT_DIR/byte_views.ll"
grep -q 'define i8 @set_tx_empty(i8 %status, i1 %flag)' "$OUT_DIR/packed_overlay.ll"
grep -q 'select i1 %flag, i8 %t.*, i8 %t' "$OUT_DIR/packed_overlay.ll"
grep -q 'define \[4 x i8\] @set_word(i32 %value)' "$OUT_DIR/packed_overlay.ll"
grep -q 'store i32 %value, ptr %word.addr' "$OUT_DIR/packed_overlay.ll"
grep -q 'define i8 @first_byte(\[4 x i8\] %word)' "$OUT_DIR/packed_overlay.ll"
grep -q 'define i64 @accept_overlay_reflection()' "$OUT_DIR/packed_bits_overlay.ll"
grep -q 'define i64 @accept_spec_overlay_reflection()' "$OUT_DIR/packed_bits_overlay.ll"
grep -q 'shl i8 %t.*, 1' "$OUT_DIR/packed_bits_overlay.ll"
grep -q 'define i8 @pick_const(\[4 x i8\] %xs)' "$OUT_DIR/const_get.ll"
grep -q 'getelementptr inbounds \[4 x i8\], ptr %xs.addr, i64 0, i64 2' "$OUT_DIR/const_get.ll"
grep -q 'define i8 @pick_checked(\[4 x i8\] %xs, i64 %i)' "$OUT_DIR/const_get.ll"
grep -q 'call void @mc_trap_Bounds()' "$OUT_DIR/const_get.ll"
grep -q 'ret i8 65' "$OUT_DIR/char_literals.ll"
grep -q 'ret i8 10' "$OUT_DIR/char_literals.ll"
grep -q 'ret i8 92' "$OUT_DIR/char_literals.ll"
grep -q '@.str.0 = private unnamed_addr constant \[13 x i8\] c"hello, world\\00"' "$OUT_DIR/string_literals.ll"
grep -q '@.str.3 = private unnamed_addr constant \[33 x i8\] c"tab\\09newline\\0Aquote\\22backslash\\5Cdone\\00"' "$OUT_DIR/string_literals.ll"
grep -q 'getelementptr inbounds \[13 x i8\], ptr @.str.0' "$OUT_DIR/string_literals.ll"
grep -q 'call i32 @puts(ptr %t' "$OUT_DIR/string_literals.ll"
grep -q '@llvm.usub.with.overflow.i8' "$OUT_DIR/char_arithmetic.ll"
grep -q 'icmp uge i8 %c, 48' "$OUT_DIR/char_arithmetic.ll"
grep -q 'declare void @consume_u32(i32)' "$OUT_DIR/statement_workflow.ll"
grep -q 'call void @consume_u32(i32 %value)' "$OUT_DIR/statement_workflow.ll"
grep -q 'call i32 @combine(i32 %left, i32 %right)' "$OUT_DIR/statement_workflow.ll"
grep -q 'load i32, ptr %out.addr' "$OUT_DIR/statement_workflow.ll"
grep -q 'call void @mc_trap_IntegerOverflow()' "$OUT_DIR/statement_workflow.ll"
grep -q 'define i32 @pure_comptime_block()' "$OUT_DIR/comptime.ll"
grep -q 'ret i32 1' "$OUT_DIR/comptime.ll"
grep -q 'define i32 @pure_comptime_nested_block()' "$OUT_DIR/comptime.ll"
grep -q 'ret i32 2' "$OUT_DIR/comptime.ll"
grep -q 'call \[4 x i32\] @make_values(i32 %seed)' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'call { \[4 x i32\], { ptr, i64 } } @make_bag(i32 %seed)' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'store \[4 x i32\] %t' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'store { \[4 x i32\], { ptr, i64 } } %t' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'getelementptr inbounds \[4 x i32\]' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'extractvalue { ptr, i64 }' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'for_body' "$OUT_DIR/aggregate_rvalues.ll"
grep -q 'declare void @mc_trap_Assert()' "$OUT_DIR/bool_conditions.ll"
grep -q 'logic_and_rhs' "$OUT_DIR/bool_conditions.ll"
grep -q 'logic_or_rhs' "$OUT_DIR/bool_conditions.ll"
grep -q 'call void @mc_trap_Assert()' "$OUT_DIR/bool_conditions.ll"
grep -q 'call i32 @next_value()' "$OUT_DIR/bool_conditions.ll"
grep -q 'call void @consume_bool(i1' "$OUT_DIR/bool_conditions.ll"
grep -q '@gain = global float 0x3FF8000000000000' "$OUT_DIR/floats.ll"
grep -q '@bias = global double -0.25' "$OUT_DIR/floats.ll"
grep -q 'fadd float' "$OUT_DIR/floats.ll"
grep -q 'fsub double' "$OUT_DIR/floats.ll"
grep -q 'fmul float' "$OUT_DIR/floats.ll"
grep -q 'fdiv double' "$OUT_DIR/floats.ll"
grep -q 'fcmp olt float' "$OUT_DIR/floats.ll"
grep -q 'fcmp une double' "$OUT_DIR/floats.ll"
grep -q 'fneg double' "$OUT_DIR/floats.ll"
grep -q 'fneg float 0x3FD3333340000000' "$OUT_DIR/float_negation.ll"
grep -q 'store float 0x3FE3333340000000' "$OUT_DIR/float_negation.ll"
grep -q 'declare void @mc_trap_Unreachable()' "$OUT_DIR/trap_never.ll"
grep -q 'define i32 @trap_as_value()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Bounds()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Unreachable()' "$OUT_DIR/trap_never.ll"
grep -q 'define void @never_returns_by_trap()' "$OUT_DIR/trap_never.ll"
grep -q 'call void @mc_trap_Assert()' "$OUT_DIR/trap_never.ll"
grep -q 'ret void' "$OUT_DIR/trap_never.ll"
grep -q 'define i32 @read_u32(i64 %addr)' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'inttoptr i64' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'load volatile i32' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'store volatile i32' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'call void asm sideeffect "pause", "~{memory}"()' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'getelementptr inbounds i8' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'define ptr @offset_address' "$OUT_DIR/unsafe_machine_ops.ll"
grep -q 'call void asm sideeffect "pause", "~{memory}"()' "$OUT_DIR/asm.ll"
grep -q 'define void @raw_store_in_unsafe(i64 %addr, i64 %value)' "$OUT_DIR/unsafe_context.ll"
grep -q 'store volatile i64 %value' "$OUT_DIR/unsafe_context.ll"
grep -q 'call void asm sideeffect "cli", "~{memory}"()' "$OUT_DIR/unsafe_context.ll"
grep -q 'define void @nested_unsafe_raw_store(i64 %addr, i8 %value)' "$OUT_DIR/unsafe_context.ll"
grep -q 'define ptr @mmio_map_in_unsafe(i64 %pa)' "$OUT_DIR/unsafe_context.ll"
grep -q 'inttoptr i64 %pa to ptr' "$OUT_DIR/unsafe_context.ll"
grep -q 'call void @mc_trap_NullUnwrap()' "$OUT_DIR/unsafe_context.ll"
grep -q 'call i64 asm sideeffect "bsf [$]1, [$]0", "=r,r,~{cc}"' "$OUT_DIR/precise_asm.ll"
grep -q 'call i64 asm "lea ([$]1,[$]1), [$]0", "=r,r"' "$OUT_DIR/precise_asm.ll"
grep -q 'store i64 %t0, ptr %out_val.addr' "$OUT_DIR/precise_asm.ll"
grep -q 'define void @putc(ptr %uart, i8 %ch)' "$OUT_DIR/mmio.ll"
grep -q 'fence release' "$OUT_DIR/mmio.ll"
grep -q 'store volatile i8 %ch, ptr %uart' "$OUT_DIR/mmio.ll"
grep -q 'load volatile i8, ptr %t' "$OUT_DIR/mmio.ll"
grep -q 'fence acquire' "$OUT_DIR/mmio.ll"
grep -q 'getelementptr inbounds i8, ptr %dev, i64 112' "$OUT_DIR/mmio_offset.ll"
grep -q 'getelementptr inbounds i8, ptr %dev, i64 128' "$OUT_DIR/mmio_offset.ll"
grep -q 'define i1 @mmio_irq(ptr %uart, i8 %value)' "$OUT_DIR/irq_context.ll"
grep -q 'store volatile i8 %value, ptr %uart' "$OUT_DIR/irq_context.ll"
grep -q 'define i1 @atomic_mmio_irq(i32 %flag, i32 %counter, ptr %uart, i32 %value, i8 %byte)' "$OUT_DIR/irq_context.ll"
grep -q 'store atomic i32 %value, ptr %flag.addr release, align 4' "$OUT_DIR/irq_context.ll"
grep -q 'atomicrmw add ptr %counter.addr, i32 %value acq_rel' "$OUT_DIR/irq_context.ll"
grep -q 'zext i1 %t.* to i8' "$OUT_DIR/mmio_ordering.ll"
grep -q 'define { ptr, i64 } @program_noncoherent_dma(ptr %eng, i64 %buf)' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'store volatile i64 %buf, ptr %eng' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'fence release' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'fence acquire' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'inttoptr i64 %buf to ptr' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'declare i8 @disable_interrupts()' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'declare void @restore_interrupts(i8)' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'define i32 @read_device(i32 %reg, i8 %cs)' "$OUT_DIR/dma_irq_markers.ll"
grep -q 'define i64 @frame_base(i64 %region_start, i64 %index)' "$OUT_DIR/addr.ll"
grep -q 'define i64 @pa_value(i64 %a)' "$OUT_DIR/addr.ll"
grep -q 'ret i64 %a' "$OUT_DIR/addr.ll"
grep -q 'declare void @takes_paddr(i64)' "$OUT_DIR/address_classes.ll"
grep -q 'define void @pass_paddr(i64 %addr)' "$OUT_DIR/address_classes.ll"
grep -q 'call void @takes_paddr(i64 %addr)' "$OUT_DIR/address_classes.ll"
grep -q 'define i64 @keep_user_ptr(i64 %ptr)' "$OUT_DIR/address_classes.ll"
grep -q 'define i64 @keep_const_user_ptr(i64 %ptr)' "$OUT_DIR/address_classes.ll"
grep -q 'define i64 @keep_phys_ptr(i64 %ptr)' "$OUT_DIR/address_classes.ll"
grep -q 'define float @load_f32(i64 %a)' "$OUT_DIR/float_buffers.ll"
grep -q 'load volatile float' "$OUT_DIR/float_buffers.ll"
grep -q 'store volatile double' "$OUT_DIR/float_buffers.ll"
grep -q 'call float @sqrtf(float %x)' "$OUT_DIR/float_buffers.ll"
grep -q 'call double @exp2(double %x)' "$OUT_DIR/float_buffers.ll"
grep -q 'define float @add_mul_sum(\[4 x float\] %a, \[4 x float\] %b)' "$OUT_DIR/vector_lanes.ll"
grep -q 'define \[4 x float\] @f32x4_load(i64 %base)' "$OUT_DIR/vector_lanes.ll"
grep -q 'getelementptr inbounds \[4 x float\]' "$OUT_DIR/vector_lanes.ll"
grep -q 'bitcast float .* to i32' "$OUT_DIR/vector_lanes.ll"
grep -q 'bitcast i32 .* to float' "$OUT_DIR/vector_lanes.ll"
grep -q '@default_error = global i64 1' "$OUT_DIR/enums_aliases.ll"
grep -q '@default_errors = global \[2 x i64\] \[i64 0, i64 2\]' "$OUT_DIR/enums_aliases.ll"
grep -q '@counts = global \[3 x i32\] \[i32 1, i32 2, i32 3\]' "$OUT_DIR/enums_aliases.ll"
grep -q '@llvm.uadd.with.overflow.i32' "$OUT_DIR/enums_aliases.ll"
grep -q 'define i8 @open_enum_raw(i8 %state)' "$OUT_DIR/enums_aliases.ll"
grep -q 'ret i8 -1' "$OUT_DIR/enums_aliases.ll"
grep -q 'ret i8 65' "$OUT_DIR/enums_aliases.ll"
grep -q 'switch i8 %irq' "$OUT_DIR/enums_aliases.ll"
grep -q 'switch i64 %error' "$OUT_DIR/enums_aliases.ll"
grep -q 'call void @mc_trap_InvalidRepresentation()' "$OUT_DIR/enums_aliases.ll"
grep -q 'define ptr @alias_raw_offset' "$OUT_DIR/enums_aliases.ll"
grep -q 'define i1 @flags_ready(i8 %flags)' "$OUT_DIR/declarations.ll"
grep -q 'and i8 %flags, 1' "$OUT_DIR/declarations.ll"
grep -q 'define i8 @keep_mode(i8 %mode)' "$OUT_DIR/declarations.ll"
grep -q '@copied_value = global i32 0' "$OUT_DIR/assignment_values.ll"
grep -q 'define i32 @global_assignment(i32 %value)' "$OUT_DIR/assignment_values.ll"
grep -q 'store i32 %value, ptr @shared_value' "$OUT_DIR/assignment_values.ll"
grep -q 'define i1 @local_shadows_global_assignment()' "$OUT_DIR/assignment_values.ll"
grep -q '@default_flags = global i8 1' "$OUT_DIR/type_aliases.ll"
grep -q 'define i32 @accept_array_alias(\[4 x i32\] %xs, i64 %i)' "$OUT_DIR/type_aliases.ll"
grep -q 'alloca \[4 x i32\]' "$OUT_DIR/type_aliases.ll"
grep -q 'define i1 @accept_packed_alias(i8 %flags)' "$OUT_DIR/type_aliases.ll"
grep -q 'icmp ne i8 .* 0' "$OUT_DIR/type_aliases.ll"
grep -q '@default_irq_value = global i8 33' "$OUT_DIR/enum_switch.ll"
grep -q 'define void @switch_expr_body_order(i8 %irq)' "$OUT_DIR/enum_switch.ll"
grep -q 'call void @consume_pair(i32 %t0, i32 %t1)' "$OUT_DIR/enum_switch.ll"
grep -q 'br label %switch_end' "$OUT_DIR/enum_switch.ll"
grep -q 'define i8 @read_state_raw()' "$OUT_DIR/enum_switch.ll"
grep -q 'declare void @mc_trap_NullUnwrap()' "$OUT_DIR/nullable_pointers.ll"
grep -q '@saved_nullable = global ptr null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define ptr @nullable_null()' "$OUT_DIR/nullable_pointers.ll"
grep -q 'ret ptr null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'icmp eq ptr %maybe, null' "$OUT_DIR/nullable_pointers.ll"
grep -q 'call void @mc_trap_NullUnwrap()' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define ptr @unwrap_or(ptr %maybe, ptr %fallback)' "$OUT_DIR/nullable_pointers.ll"
grep -q 'nullable_some' "$OUT_DIR/nullable_pointers.ll"
grep -q 'br i1 .* label %nullable_some.*, label %nullable_none.*, !dbg !' "$OUT_DIR/nullable_pointers.ll"
grep -q 'define i32 @nullable_switch(ptr %maybe)' "$OUT_DIR/nullable_pointers.ll"
grep -q 'call ptr @maybe_ptr_from' "$OUT_DIR/nullable_pointers.ll"
grep -q '@ticks = global i32 0' "$OUT_DIR/atomics.ll"
grep -q 'load atomic i8, ptr .* acquire, align 1' "$OUT_DIR/atomics.ll"
grep -q 'trunc i8 .* to i1' "$OUT_DIR/atomics.ll"
grep -q 'zext i1 %value to i8' "$OUT_DIR/atomics.ll"
grep -q 'store atomic i8 .* ptr .* release, align 1' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr .* i64 %delta acq_rel' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw sub ptr .* i32 %delta release' "$OUT_DIR/atomics.ll"
grep -q 'monotonic, align 1' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr .* i32 %delta seq_cst' "$OUT_DIR/atomics.ll"
grep -q 'atomicrmw add ptr @ticks, i32 1 acq_rel' "$OUT_DIR/atomics.ll"
grep -q 'load atomic i32, ptr @ticks acquire, align 4' "$OUT_DIR/atomics.ll"
grep -q 'store atomic i32 0, ptr @ticks release, align 4' "$OUT_DIR/atomics.ll"
grep -q '@default_op = global ptr @add' "$OUT_DIR/fn_pointers.ll"
grep -q '@default_ops = global \[2 x ptr\] \[ptr @add, ptr @mul\]' "$OUT_DIR/fn_pointers.ll"
grep -q '@default_box = global { ptr } { ptr @add }' "$OUT_DIR/fn_pointers.ll"
grep -q 'define i32 @apply(ptr %op, i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q 'call i32 %op(i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q 'ret ptr @tick' "$OUT_DIR/fn_pointers.ll"
grep -q 'load ptr, ptr @default_op' "$OUT_DIR/fn_pointers.ll"
grep -q 'getelementptr inbounds \[2 x ptr\], ptr @default_ops' "$OUT_DIR/fn_pointers.ll"
grep -q 'getelementptr inbounds { ptr }, ptr %o, i64 0, i32 0' "$OUT_DIR/fn_pointers.ll"
grep -q 'call i32 @dispatch(ptr %op.addr, i32 %x, i32 %y)' "$OUT_DIR/fn_pointers.ll"
grep -q '@copied_box = global { ptr } { ptr @add }' "$OUT_DIR/fn_pointer_full.ll"
grep -q '@default_boxes = global \[2 x { ptr }\] \[{ ptr } { ptr @add }, { ptr } { ptr @mul }\]' "$OUT_DIR/fn_pointer_full.ll"
grep -q 'define i32 @copied_global_box_call(i32 %x, i32 %y)' "$OUT_DIR/fn_pointer_full.ll"
grep -q 'store { ptr } %t.*, ptr %t.*' "$OUT_DIR/fn_pointer_full.ll"
grep -q 'store ptr @add, ptr %t' "$OUT_DIR/fn_pointer_full.ll"
grep -q 'define \[2 x i32\] @assign_array_literal()' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'alloca \[2 x i32\]' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'store \[2 x i32\] %t' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'store { i32, i32 } %t' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds \[2 x \[2 x i32\]\], ptr @matrix' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds { \[2 x \[2 x i32\]\] }, ptr @box' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'getelementptr inbounds \[2 x { \[2 x i32\] }\], ptr @row_boxes' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'call i32 @consume_row(\[2 x i32\]' "$OUT_DIR/aggregate_assignments.ll"
grep -q 'call i32 @consume_pair({ i32, i32 }' "$OUT_DIR/aggregate_assignments.ll"
grep -q '@default_pair = global { i32, i32 } { i32 1, i32 2 }' "$OUT_DIR/struct_literals.ll"
grep -q 'define { { i32, i32 } } @make_pair_box()' "$OUT_DIR/struct_literals.ll"
grep -q 'call void @consume_pair({ i32, i32 }' "$OUT_DIR/struct_literals.ll"
grep -q 'define i32 @inferred_call_field_pair()' "$OUT_DIR/struct_literals.ll"
grep -q 'define \[2 x i32\] @return_call_array()' "$OUT_DIR/array_values.ll"
grep -q 'define \[2 x i32\] @copy_array(\[2 x i32\] %xs)' "$OUT_DIR/array_values.ll"
grep -q 'call void @consume_array(\[2 x i32\]' "$OUT_DIR/array_values.ll"
grep -q 'store \[2 x i32\] %xs, ptr %xs.addr' "$OUT_DIR/array_values.ll"
grep -q 'define i32 @use_u32(i32 %x, i32 %y)' "$OUT_DIR/generic_structs.ll"
grep -q 'call { i32, i32 } @make_pair__u32' "$OUT_DIR/generic_structs.ll"
grep -q 'call { i8, i8 } @make_pair__u8' "$OUT_DIR/generic_structs.ll"
grep -q 'define { i1, { i32, i32 }, i8 } @make_pair_result(i32 %x, i32 %y)' "$OUT_DIR/generic_structs.ll"
grep -q 'define i32 @unwrap_pair_result({ i1, { i32, i32 }, i8 } %result)' "$OUT_DIR/generic_structs.ll"
grep -q 'define \[4 x i8\] @fill__4(i8 %value)' "$OUT_DIR/monomorphize.ll"
grep -q 'define \[8 x i8\] @fill__8(i8 %value)' "$OUT_DIR/monomorphize.ll"
grep -q 'define i64 @reflected_box_size__u32()' "$OUT_DIR/monomorphize.ll"
grep -q 'ret i64 4' "$OUT_DIR/monomorphize.ll"
grep -q 'define i32 @explicit_grouped_uninit_scalar(i32 %value)' "$OUT_DIR/initialization.ll"
grep -q 'store i32 0, ptr %x.addr' "$OUT_DIR/initialization.ll"
grep -q 'store \[4 x i8\] zeroinitializer, ptr %buf.addr' "$OUT_DIR/initialization.ll"
grep -q 'define i32 @maybe_uninit_write_assume_init()' "$OUT_DIR/initialization.ll"
grep -q 'store { i32 } %t.*, ptr %x.addr' "$OUT_DIR/initialization.ll"
grep -q 'load { i32 }, ptr %x.addr' "$OUT_DIR/initialization.ll"
grep -q 'define { i1, i32, i8 } @make_ok(i32 %value)' "$OUT_DIR/result.ll"
grep -q 'insertvalue { i1, i32, i8 } undef, i1 true, 0' "$OUT_DIR/result.ll"
grep -q 'call void @mc_trap_InvalidRepresentation()' "$OUT_DIR/result.ll"
grep -q 'define i32 @result_switch_value({ i1, i32, i8 } %result)' "$OUT_DIR/result.ll"
grep -q 'br i1 .* label %result_ok.*, label %result_err.*, !dbg !' "$OUT_DIR/result.ll"
grep -q 'define i32 @result_payloadless_switch()' "$OUT_DIR/result.ll"
grep -q 'define { i1, i8, { i32 } } @ok_marker()' "$OUT_DIR/void_result.ll"
grep -q 'define { i1, i8, { i32 } } @err_marker({ i32 } %e)' "$OUT_DIR/void_result.ll"
grep -q 'define i32 @switch_result_ok_binding_type({ i1, i32, i8 } %result)' "$OUT_DIR/if_let_narrowing.ll"
grep -q 'define { i1, i32, { i32 } } @try_in_constructor()' "$OUT_DIR/try_in_expressions.ll"
grep -q 'define { i1, i32, { i32 } } @two_tries_in_arith()' "$OUT_DIR/try_in_expressions.ll"
grep -q 'define { i1, i32, i8 } @assign_result_try()' "$OUT_DIR/try_propagation.ll"
grep -q 'try_err' "$OUT_DIR/try_propagation.ll"
grep -q 'define { i1, i32, i8 } @result_try_call_expr_rhs_after_call()' "$OUT_DIR/try_propagation.ll"
grep -q 'define i32 @cleanup_before_return()' "$OUT_DIR/defer.ll"
grep -q 'call void @close_b()' "$OUT_DIR/defer.ll"
grep -q 'call void @close_a()' "$OUT_DIR/defer.ll"
grep -q 'call void @close_pair(i32 %t0, i32 %t1)' "$OUT_DIR/defer.ll"
grep -q 'define void @cleanup_before_break(i1 %flag)' "$OUT_DIR/defer_cleanup.ll"
grep -q 'call void @close_resource()' "$OUT_DIR/defer_cleanup.ll"
grep -q 'define i8 @narrow_trap(i32 %x)' "$OUT_DIR/conversions.ll"
grep -q 'trap_conversion' "$OUT_DIR/conversions.ll"
grep -q 'select i1 .* i32 255' "$OUT_DIR/conversions.ll"
grep -q 'define i32 @raw(i32 %word)' "$OUT_DIR/conversions.ll"
grep -q 'define i32 @wrap_add(i32 %a, i32 %b)' "$OUT_DIR/arithmetic_domains.ll"
grep -q '  %t0 = add i32 %a, %b' "$OUT_DIR/arithmetic_domains.ll"
grep -q 'call void @mc_trap_InvalidShift()' "$OUT_DIR/arithmetic_domains.ll"
grep -q 'select i1 .* i32 4294967295' "$OUT_DIR/arithmetic_domains.ll"
grep -q '@llvm.usub.with.overflow.i32' "$OUT_DIR/arithmetic_domains.ll"
grep -q '@llvm.umul.with.overflow.i16' "$OUT_DIR/arithmetic_domains.ll"
grep -q 'define i1 @seq_before(i32 %a, i32 %b)' "$OUT_DIR/serial_counter.ll"
grep -q 'icmp slt i32 .* 0' "$OUT_DIR/serial_counter.ll"
grep -q 'define i1 @seq_after(i32 %a, i32 %b)' "$OUT_DIR/serial_counter.ll"
grep -q 'icmp sgt i32 .* 0' "$OUT_DIR/serial_counter.ll"
grep -q 'define i32 @seq_distance(i32 %a, i32 %b)' "$OUT_DIR/serial_counter.ll"
grep -q 'define i64 @tick_delta(i64 %now, i64 %start)' "$OUT_DIR/serial_counter.ll"
grep -q 'define { i1, i8, i8 } @seq_compare(i32 %a, i32 %b)' "$OUT_DIR/library_results.ll"
grep -q 'icmp eq i32 .* -2147483648' "$OUT_DIR/library_results.ll"
grep -q 'define { i1, i64, i8 } @tick_bounded(i64 %now, i64 %start, i64 %max)' "$OUT_DIR/library_results.ll"
grep -q 'icmp ule i64' "$OUT_DIR/library_results.ll"
grep -q 'define { i1, i8, i8 } @narrow_try(i32 %x)' "$OUT_DIR/library_results.ll"
grep -q 'icmp ugt i32 %x, 255' "$OUT_DIR/library_results.ll"
grep -q 'define { i1, i64, i8 } @widen_try(i8 %x)' "$OUT_DIR/library_results.ll"
grep -q 'define { i1, i32, i8 } @sum_u32({ ptr, i64 } %xs)' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'alloca i128' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'zext i32 .* to i128' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'sext i32 .* to i128' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'icmp sgt i128 .* 4294967295' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'icmp slt i128 .* -2147483648' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'define double @sum_left_f64({ ptr, i64 } %xs)' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'fadd double' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'define float @sum_fast_f32({ ptr, i64 } %xs)' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'fadd reassoc float' "$OUT_DIR/reduce_sum_checked.ll"
grep -q 'define i32 @wrap_add(i32 %a, i32 %b)' "$OUT_DIR/wrapping_builtin.ll"
grep -q '  %t0 = add i32 %a, %b' "$OUT_DIR/wrapping_builtin.ll"
grep -q 'sub i32 0, %a' "$OUT_DIR/no_lang_trap.ll"
grep -q 'select i1 .* i32 4294967295' "$OUT_DIR/no_lang_trap.ll"
grep -q 'define i32 @unchecked_add_inside_contract(i32 %a, i32 %b)' "$OUT_DIR/unsafe_contract.ll"
grep -q 'define i32 @unchecked_add_return_order()' "$OUT_DIR/unsafe_contract.ll"
grep -q '  %t.* = add i32' "$OUT_DIR/unsafe_contract.ll"
grep -q 'define void @noalias_contract_region(ptr %p, i64 %n)' "$OUT_DIR/unsafe_contract_scope.ll"
grep -q 'ptrtoint ptr' "$OUT_DIR/unsafe_contract_scope.ll"
grep -q 'store volatile i8 2' "$OUT_DIR/unsafe_contract_scope.ll"
grep -q 'declare { i32, \[4 x i8\], \[2 x i64\] } @make_token()' "$OUT_DIR/tagged_union.ll"
grep -q 'define { i32, \[4 x i8\], \[2 x i64\] } @make_number()' "$OUT_DIR/tagged_union.ll"
grep -q 'define i64 @token_value({ i32, \[4 x i8\], \[2 x i64\] } %token)' "$OUT_DIR/tagged_union.ll"
grep -q 'define i64 @token_call_seed_value()' "$OUT_DIR/tagged_union.ll"
grep -q 'switch i32 .*%union_switch_arm' "$OUT_DIR/tagged_union.ll"
grep -q '\], !dbg !' "$OUT_DIR/tagged_union.ll"
grep -q '@raws = global \[2 x ptr\] \[ptr getelementptr inbounds' "$OUT_DIR/global_initializers.ll"
grep -q '@first_value_ptr = global ptr getelementptr inbounds' "$OUT_DIR/global_initializers.ll"
grep -q '@default_slice = global { ptr, i64 } zeroinitializer' "$OUT_DIR/global_initializers.ll"
grep -q '@.str.*c"raw-a\\00"' "$OUT_DIR/global_initializers.ll"
grep -q 'define i64 @accept_spec_repr_of_tagged_union()' "$OUT_DIR/reflection.ll"
grep -q 'ret i64 4' "$OUT_DIR/reflection.ll"
grep -q 'define i64 @accept_spec_sizeof_dma_buf()' "$OUT_DIR/reflection.ll"
grep -q 'define i16 @reflect_identity__u16(i16 %value)' "$OUT_DIR/reflection.ll"
grep -q 'call i32 @reflect_identity__u32(i32' "$OUT_DIR/reflection.ll"
grep -q '@g_slot = global { { ptr, ptr }, ptr, i1 } zeroinitializer' "$OUT_DIR/global_closure.ll"
grep -q 'insertvalue { ptr, ptr } zeroinitializer, ptr @run_impl, 0' "$OUT_DIR/global_closure.ll"
grep -q 'extractvalue { ptr, ptr } %t' "$OUT_DIR/global_closure.ll"
grep -q 'call i32 %t.*(ptr %t.*, i32 %x)' "$OUT_DIR/global_closure.ll"
