#!/usr/bin/env python3
"""Seedable generator of move-resource MC programs for the leak-invariant differential fuzzer.

Each program defines a linear `move` test resource whose construction/destruction adjusts a
global `live_count`. Generated `inner_*` functions allocate resources, reserve their release
with `defer` (and exercise move *transfer* through `relabel`), then run random control flow
with early returns — so the deferred frees must fire on EVERY exit path. `harness()` calls them
in a loop and counts any moment where `live_count` failed to return to 0, returning that count.

Invariant: a correct backend always returns 0 (every resource released exactly once, on every
path), and both backends must agree. A dropped defer leaves live_count != 0 (bad > 0); a double
release underflows free_res's checked subtraction and traps — both observable and divergent.

Usage: mcgen_move.py <seed>   # prints one MC program to stdout (deterministic per seed)
"""
import random
import sys

PRELUDE = """\
// Generated by tools/toolchain/mcgen_move.py — do not edit; regenerate from the seed.
move struct TestRes { id: u64 }
global live_count: u64;
global next_id: u64;
fn make_res() -> TestRes {
    live_count = live_count + 1;
    next_id = next_id + 1;
    return .{ .id = next_id };
}
fn free_res(r: TestRes) -> void {
    live_count = live_count - 1; // checked: a double release underflows and traps
    unsafe { forget_unchecked(r); }
}
fn relabel(r: TestRes) -> TestRes { return r; } // pure move transfer (live_count unchanged)
fn live() -> u64 { return live_count; }
enum Fault { Bad, Other }
// A fallible step: its `?` in an inner function early-returns the error, so the deferred frees
// already in scope must still fire on that error edge.
fn fallible(flag: u64) -> Result<u64, Fault> {
    if (flag % 4) == 0 { return err(.Bad); }
    if (flag % 4) == 1 { return err(.Other); }
    return ok(flag);
}
"""


class Gen:
    def __init__(self, seed):
        self.rng = random.Random(seed)

    def u64(self, flag="flag"):
        r = self.rng.random()
        if r < 0.4:
            return "%s" % flag
        if r < 0.7:
            return str(self.rng.randrange(0, 100))
        return "(%s %% %d)" % (flag, self.rng.choice((2, 3, 4)))

    def control_tail(self, out, indent, depth):
        # Emit a Result<u64,Fault> body that returns on every path — via ok/err early returns and
        # `?` propagation — all of which must still run the function's deferred frees.
        pad = "    " * indent
        if self.rng.random() < 0.5:
            # a fallible step whose `?` may early-return the error (defers must fire on that edge)
            self.qcount += 1
            out.append("%slet q%d: u64 = fallible(%s)?;" % (pad, self.qcount, self.u64()))
        if depth < 2 and self.rng.random() < 0.6:
            k = self.rng.choice((2, 3))
            c = self.rng.randrange(k)
            out.append("%sif (flag %% %d) == %d {" % (pad, k, c))
            r = self.rng.random()
            if r < 0.4:
                out.append("%s    return ok(%s);" % (pad, self.u64()))   # early return: defers fire
            elif r < 0.6:
                out.append("%s    return err(.Bad);" % pad)             # early error return: defers fire
            else:
                self.control_tail(out, indent + 1, depth + 1)
            out.append("%s}" % pad)
        out.append("%sreturn ok(%s);" % (pad, self.u64()))

    def inner(self, idx):
        self.qcount = 0
        out = []
        out.append("fn inner_%d(flag: u64) -> Result<u64, Fault> {" % idx)
        nres = self.rng.randrange(1, 4)
        for j in range(nres):
            if self.rng.random() < 0.5:
                # allocate + transfer through relabel, then defer-free the transferred handle
                out.append("    let a%d: TestRes = make_res();" % j)
                out.append("    let r%d: TestRes = relabel(a%d);" % (j, j))
                out.append("    defer free_res(r%d);" % j)
            else:
                out.append("    let r%d: TestRes = make_res();" % j)
                out.append("    defer free_res(r%d);" % j)
        self.control_tail(out, 1, 0)
        out.append("}")
        return "\n".join(out)

    def program(self):
        ninner = self.rng.randrange(2, 5)
        parts = [PRELUDE]
        for i in range(ninner):
            parts.append(self.inner(i))
        body = []
        body.append("export fn harness() -> u64 {")
        body.append("    var bad: u64 = 0;")
        body.append("    var i: u64 = 0;")
        body.append("    while i < 8 {")
        for i in range(ninner):
            body.append("        switch inner_%d(i + %d) {" % (i, self.rng.randrange(0, 5)))
            body.append("            ok(v) => {}")
            body.append("            err(f) => {}")
            body.append("        }")
            body.append("        if live() != 0 { bad = bad + 1; }") # defers must fire on every path
        body.append("        i = i + 1;")
        body.append("    }")
        body.append("    return bad;")
        body.append("}")
        parts.append("\n".join(body))
        return "\n\n".join(parts) + "\n"


def main():
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    sys.stdout.write(Gen(seed).program())
    return 0


if __name__ == "__main__":
    sys.exit(main())
