#!/usr/bin/env python3
"""Seedable generator of small, type-correct, trap-free MC programs for differential testing.

Every program is built from a fixed prelude (a wrap<u64> domain `W`, a side-effecting `tick()`
that increments a global, and `w`/`add`/`mul`/`dig` helpers) plus a randomly generated
`export fn harness() -> u64` body. The body uses only operations that cannot trap — wrap
(modular) arithmetic, `% k` with constant k >= 2, constant-bounded loops — so the only thing
that can differ between the C and LLVM backends is *codegen*: evaluation order (tick() side
effects), switch/if lowering, loop lowering, ABI. The harness returns a digest of the computed
state; both backends must return the same digest.

Usage: mcgen.py <seed>   # prints one MC program to stdout (deterministic per seed)
"""
import random
import sys

PRELUDE = """\
// Generated by tools/toolchain/mcgen.py — do not edit; regenerate from the seed.
type W = wrap<u64>;
global g_seq: W;
fn w(x: u64) -> W { return W.from(x); }
fn tick() -> W { g_seq = g_seq + w(1); return g_seq; }
fn add(a: W, b: W) -> W { return a + b; }
fn mul(a: W, b: W) -> W { return a * b; }
fn dig(x: W) -> u64 { return x as u64; }
"""


class Gen:
    def __init__(self, seed):
        self.rng = random.Random(seed)
        self.nvars = 0          # live W locals: v0..v{nvars-1}
        self.nloops = 0         # loop counter index
        self.budget = 40        # statement budget (keeps programs bounded)
        self.depth = 0          # nesting depth guard

    # ----- expressions (all of type W, trap-free) -----
    def wexpr(self, d=0):
        # Leaves bias higher as depth grows so expressions terminate.
        if d >= 3 or self.rng.random() < 0.35 + 0.2 * d:
            choice = self.rng.random()
            if choice < 0.45 and self.nvars > 0:
                return "v%d" % self.rng.randrange(self.nvars)
            if choice < 0.75:
                return "tick()"                        # side effect: order-sensitive
            return "w(%d)" % self.rng.randrange(0, 1000)
        op = self.rng.choice(("add", "mul"))
        return "%s(%s, %s)" % (op, self.wexpr(d + 1), self.wexpr(d + 1))

    # A u64 control value in [0, k): dig(<wexpr>) % k, never a divide-by-zero (k >= 2).
    def u64_mod(self, k):
        return "dig(%s) %% %d" % (self.wexpr(), k)

    # ----- statements -----
    def stmt(self, out, indent):
        if self.budget <= 0:
            return
        self.budget -= 1
        pad = "    " * indent
        # New W locals are declared only at the top level (depth 0); the digest folds every
        # top-level local at the end, and a local declared inside a nested block would be out of
        # scope there. Nested blocks only mutate existing locals or branch/loop.
        can_decl = self.depth == 0
        r = self.rng.random()
        if can_decl and r < 0.40:
            out.append("%svar v%d: W = %s;" % (pad, self.nvars, self.wexpr()))
            self.nvars += 1
        elif r < 0.62:
            # mutate an existing local (avoid a trivial `vN = vN` self-assignment)
            t = self.rng.randrange(self.nvars)
            rhs = self.wexpr()
            if rhs == "v%d" % t:
                rhs = "add(%s, tick())" % rhs
            out.append("%sv%d = %s;" % (pad, t, rhs))
        elif r < 0.76 and self.depth < 3:
            # if / else
            k = self.rng.choice((2, 3, 4))
            c = self.rng.randrange(k)
            out.append("%sif %s == %d {" % (pad, self.u64_mod(k), c))
            self.block(out, indent + 1)
            out.append("%s} else {" % pad)
            self.block(out, indent + 1)
            out.append("%s}" % pad)
        elif r < 0.90 and self.depth < 3:
            # switch with an exhaustive default
            k = self.rng.choice((2, 3))
            out.append("%sswitch (%s) {" % (pad, self.u64_mod(k)))
            for arm in range(k - 1):
                out.append("%s    %d => {" % (pad, arm))
                self.block(out, indent + 2)
                out.append("%s    }" % pad)
            out.append("%s    _ => {" % pad)
            self.block(out, indent + 2)
            out.append("%s    }" % pad)
            out.append("%s}" % pad)
        else:
            # bounded loop
            n = self.rng.randrange(1, 6)
            i = self.nloops
            self.nloops += 1
            t = self.rng.randrange(self.nvars)
            out.append("%svar i%d: u64 = 0;" % (pad, i))
            out.append("%swhile i%d < %d {" % (pad, i, n))
            out.append("%s    v%d = add(v%d, tick());" % (pad, t, t))
            out.append("%s    i%d = i%d + 1;" % (pad, i, i))
            out.append("%s}" % pad)

    def block(self, out, indent):
        self.depth += 1
        n = self.rng.randrange(1, 4)
        for _ in range(n):
            self.stmt(out, indent)
        self.depth += -1

    def program(self):
        out = []
        # Always start with one top-level local so nested blocks have something to mutate, then
        # a few more statements, then fold every top-level local into the digest.
        out.append("    var v0: W = tick();")
        self.nvars = 1
        nstmts = self.rng.randrange(4, 10)
        for _ in range(nstmts):
            self.stmt(out, 1)
        acc = "v0"
        for k in range(1, self.nvars):
            acc = "add(%s, v%d)" % (acc, k)
        out.append("    return dig(%s);" % acc)
        return PRELUDE + "\nexport fn harness() -> u64 {\n" + "\n".join(out) + "\n}\n"


def main():
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    sys.stdout.write(Gen(seed).program())
    return 0


if __name__ == "__main__":
    sys.exit(main())
