const diagnostics = @import("diagnostics.zig");

pub const Token = struct {
    kind: Kind,
    lexeme: []const u8,
    span: diagnostics.Span,
};

pub const Kind = enum {
    eof,
    invalid,
    identifier,
    integer_literal,
    float_literal,
    string_literal,
    char_literal,

    kw_alignof,
    kw_asm,
    kw_assert,
    kw_atomic,
    kw_bool,
    kw_break,
    kw_comptime,
    kw_const,
    kw_continue,
    kw_defer,
    kw_else,
    kw_enum,
    kw_err,
    kw_export,
    kw_extern,
    kw_false,
    kw_fn,
    kw_for,
    kw_if,
    kw_let,
    kw_match,
    kw_mut,
    kw_never,
    kw_null,
    kw_ok,
    kw_open,
    kw_overlay,
    kw_packed,
    kw_pub,
    kw_return,
    kw_sat,
    kw_serial,
    kw_sizeof,
    kw_struct,
    kw_switch,
    kw_true,
    kw_type,
    kw_union,
    kw_uninit,
    kw_unsafe,
    kw_unreachable,
    kw_use,
    kw_var,
    kw_void,
    kw_while,
    kw_wrap,

    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    comma,
    dot,
    colon,
    double_colon,
    semicolon,
    question,
    hash,
    at,
    underscore,

    plus,
    minus,
    star,
    slash,
    percent,
    amp,
    pipe,
    caret,
    tilde,
    bang,
    equal,
    less,
    greater,

    arrow,
    fat_arrow,
    equal_equal,
    bang_equal,
    less_equal,
    greater_equal,
    amp_amp,
    pipe_pipe,
    shift_left,
    shift_right,
    dot_dot,
};

pub fn keywordKind(text: []const u8) ?Kind {
    const Entry = struct { name: []const u8, kind: Kind };
    const entries = [_]Entry{
        .{ .name = "alignof", .kind = .kw_alignof },
        .{ .name = "asm", .kind = .kw_asm },
        .{ .name = "assert", .kind = .kw_assert },
        .{ .name = "atomic", .kind = .kw_atomic },
        .{ .name = "bool", .kind = .kw_bool },
        .{ .name = "break", .kind = .kw_break },
        .{ .name = "comptime", .kind = .kw_comptime },
        .{ .name = "const", .kind = .kw_const },
        .{ .name = "continue", .kind = .kw_continue },
        .{ .name = "defer", .kind = .kw_defer },
        .{ .name = "else", .kind = .kw_else },
        .{ .name = "enum", .kind = .kw_enum },
        .{ .name = "err", .kind = .kw_err },
        .{ .name = "export", .kind = .kw_export },
        .{ .name = "extern", .kind = .kw_extern },
        .{ .name = "false", .kind = .kw_false },
        .{ .name = "fn", .kind = .kw_fn },
        .{ .name = "for", .kind = .kw_for },
        .{ .name = "if", .kind = .kw_if },
        .{ .name = "let", .kind = .kw_let },
        .{ .name = "match", .kind = .kw_match },
        .{ .name = "mut", .kind = .kw_mut },
        .{ .name = "never", .kind = .kw_never },
        .{ .name = "null", .kind = .kw_null },
        .{ .name = "ok", .kind = .kw_ok },
        .{ .name = "open", .kind = .kw_open },
        .{ .name = "overlay", .kind = .kw_overlay },
        .{ .name = "packed", .kind = .kw_packed },
        .{ .name = "pub", .kind = .kw_pub },
        .{ .name = "return", .kind = .kw_return },
        .{ .name = "sat", .kind = .kw_sat },
        .{ .name = "serial", .kind = .kw_serial },
        .{ .name = "sizeof", .kind = .kw_sizeof },
        .{ .name = "struct", .kind = .kw_struct },
        .{ .name = "switch", .kind = .kw_switch },
        .{ .name = "true", .kind = .kw_true },
        .{ .name = "type", .kind = .kw_type },
        .{ .name = "union", .kind = .kw_union },
        .{ .name = "uninit", .kind = .kw_uninit },
        .{ .name = "unsafe", .kind = .kw_unsafe },
        .{ .name = "unreachable", .kind = .kw_unreachable },
        .{ .name = "use", .kind = .kw_use },
        .{ .name = "var", .kind = .kw_var },
        .{ .name = "void", .kind = .kw_void },
        .{ .name = "while", .kind = .kw_while },
        .{ .name = "wrap", .kind = .kw_wrap },
    };
    for (entries) |entry| {
        if (std.mem.eql(u8, text, entry.name)) return entry.kind;
    }
    return null;
}

const std = @import("std");
